### ISSUE TITLE
Use `()` instead of `libc::c_void`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1000]
https://github.com/PistonDevelopers/piston/blob/master/src/window/src/lib.rs#L14

This could get rid of the `libc` dependency.

- [ ] Remove libc dependency from pistoncore-window
- [ ] Bump pistoncore-window to 0.14.0
- [ ] Bump pistoncore-event_loop 0.16.0
- [ ] Bump piston to 0.16.0

**Comment by mitchmindtree** [comment]
I've also noticed the use of `()` as a replacement for `libc::c_void` - maybe this could be nice so that a user doesn't even need to import any types at all?

**Comment by bvssvni** [comment]
I'm getting "mismatched types" error for all the window backends, both for `()` and `std::os::raw::c_void`.

**Comment by bvssvni** [comment]
Seems Glutin is planning to use `()`. https://github.com/tomaka/glutin/pull/652

**Comment by bvssvni** [comment]
I opened https://github.com/AngryLawyer/rust-sdl2/issues/465.

**Comment by bvssvni** [comment]
Looks like changing to `()` in Glutin is motivated by avoiding another libc breaking change.

**Comment by bvssvni** [comment]
- [x] sdl2_window is ready
- [ ] glfw_window
- [ ] glutin_window

**Comment by bvssvni** [comment]
Window backends are now ready for this change. I wrote down a todo list in top comment. Need to go, so unless somebody else does this, I'll do it later.
