### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1009]
Earlier discussion https://github.com/PistonDevelopers/pistondevelopers.github.io/issues/89

Restarting this discussion since it has been a while.

**Comment by bvssvni** [comment]
I think that both the [GeoRust](https://github.com/georust) and [RustAudio](https://github.com/rustaudio) logos are good because of two things:

1. It is easy to associate the language Rust with the project.
2. The logo explains what the project is about.

Unfortunately, a picture of an engine piston is perhaps not that easy to recognize.

**Comment by bvssvni** [comment]
One idea is to use a 3D logo, which could make it easier to get the shape.

**Comment by bvssvni** [comment]
There is an new Rust crab logo https://www.reddit.com/r/rust/comments/41lehr/i_made_an_alternative_rust_crab/,

**Comment by bvssvni** [comment]
Here is an idea:

![assembling](https://cloud.githubusercontent.com/assets/1743862/13330385/fc1402f4-dbf8-11e5-98ef-ea124e2accb5.png)

What I'm trying to communicate with this logo:

- Thinking outside of the box
- Experimenting and building
- Rust as tool

**Comment by bvssvni** [comment]
The "P" can be used for short logo:

![p](https://cloud.githubusercontent.com/assets/1743862/13332085/a88d4214-dc00-11e5-8728-8ea93cba9efd.png)

The font is "PT Sans Bold". I took the dot from the "i" and put it inside the "P" with some rotation.

GIMP file for the whole logo:

[logo.xcf.zip](https://github.com/PistonDevelopers/piston/files/147184/logo.xcf.zip)

**Comment by LaylConway** [comment]
To be entirely frank what this logo looks like to me is a mess of badly connected parts that don't fit well together.

**Comment by bvssvni** [comment]
@LaylConway Thanks for being honest!

**Comment by bvssvni** [comment]
Trying some other ideas.

A problem with "P" inside the chainring is the space looks either out of balance or out of center.

What about putting the chainring on top of the "P"?

![piston-logo-chainring](https://cloud.githubusercontent.com/assets/1743862/13336852/9ed000a0-dc18-11e5-95b5-20b83967a792.png)

The dot is rotated 39.54 degrees which cone of this slope has equal distance climbing over the top as walking around.

**Comment by LaylConway** [comment]
I'm personally very much a fan of clean design, what if the chainring is instead replacing the O, and the other letters stay intact. It's very simple and clean.

**Comment by bvssvni** [comment]
Like this?

![piston-replace-o](https://cloud.githubusercontent.com/assets/1743862/13541875/55032068-e25f-11e5-83d6-834978c6e97a.png)

**Comment by bvssvni** [comment]
@rbrs had a suggestion earlier https://github.com/PistonDevelopers/pistondevelopers.github.io/issues/89#issuecomment-59765272:

![logo](https://camo.githubusercontent.com/7c7dd27f25ac4a036e5c41da32b2c79e780ed516/687474703a2f2f692e696d6775722e636f6d2f756c6564506e4f2e706e67)

Perhaps we could put the left one in place of the O?

**Comment by bvssvni** [comment]
I need some cleanup, but here is the idea:

![piston-logo-rbrs](https://cloud.githubusercontent.com/assets/1743862/13542484/67160b36-e263-11e5-8626-e4522d2931f4.png)

**Comment by bvssvni** [comment]
Another idea is to separate the piston and the chainring, using the piston as "i" and the chainring as "o":

![piston-logo-separate](https://cloud.githubusercontent.com/assets/1743862/13542731/fe121e0c-e264-11e5-9c38-8f42025a9fe4.png)

**Comment by sinistersnare** [comment]
I think making a P with a piston could be cool.

**Comment by LaylConway** [comment]
I think the one with just the O replaced with the logo with the piston in it is nicer, it looks cleaner.

**Comment by bvssvni** [comment]
I've updated the logo with @LaylConway 's idea. https://github.com/PistonDevelopers/piston/pull/1042

**Comment by Blacktiger** [comment]
How about a P made out of a piston connected to the chainring?

**Comment by bvssvni** [comment]
@Blacktiger Sounds like a good idea! I'll try it out when I get time.

**Comment by bvssvni** [comment]
Closing.
