### ISSUE TITLE
All members have now default permissions set to Admin

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1011]
Github updated the organization permission structure, which allows more flexibility.

All members of PistonDevelopers can now create repositories and invite outside collaborators to a project. This means, if somebody does not want to watch all repositories by default, and is only interested in a single project, they can join that project as an outside collaborator.

**Comment by xaviershay** [comment]
Fantastic, I was certainly subscribed to way more than I was interested in when I initially became a collaborator :)
