### ISSUE TITLE
Drawing charts

### ISSUE THREAD

**Issue by winding-lines** [PistonDevelopers/piston#1012]
Hi guys,

I have some very initial code for drawing line charts here 
https://github.com/winding-lines/piston-chart

Part of the code (computing nice grids) is not dependent on Conrod, but the LineChart widget is. The cargo setup uses an optional "widget" feature to model this dual dependency.

The margins and grid are off, I hope to fix that over the next couple of days. I am doing this slightly premature announcement to judge the level of interest.

**Comment by bvssvni** [comment]
Nice! I'm very interested in this...

**Comment by winding-lines** [comment]
Great :-)

I pushed some more fixes to the grid. My focus in on representing multiple
time series on the same chart so I will be adding code in that direction.

Right now the Time LabelFormatter generates labels with the full
year/month/day and most of the time I just need the minute.

The overall architecture is still in flux. Let me know if you have feedback
on the design and/or you would like to contribute some code.

**Comment by winding-lines** [comment]
I am struggling using piston-cargo from github in a top level application.

Package `piston-chart v0.1.0 (
https://github.com/winding-lines/piston-chart.git#a192300d)` does not have
these features: `widgets`

Would you guys be ok if I publish piston-chart to crates.io to see if it
will fix this issue?

Marius

**Comment by bvssvni** [comment]
@winding-lines Try this:

```
[dependencies.piston-chart]
git = "https://github.com/winding-lines/piston-chart"
```

**Comment by winding-lines** [comment]
Thanks Sven, I just had to do 'cargo update' :-)

Marius
---

**Comment by bvssvni** [comment]
I've added the label "Information" so people can find this issue later by search. Closing discussion since it would be better to do this on the issue tracker on the project.
