### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by walkblank** [PistonDevelopers/piston#1015]
C:\Users\xsmdesign03\.cargo\registry\src\github.com-0a35038f75765ae4\pistoncore-
glutin_window-0.16.0\src/lib.rs:95:27: 95:53 error: mismatched types:
 expected `*const libc::types::common::c95::c_void`,
    found `*const ()`
(expected enum `libc::types::common::c95::c_void`,
    found ()) [E0308]
C:\Users\xsmdesign03\.cargo\registry\src\github.com-0a35038f75765ae4\pistoncore-
glutin_window-0.16.0\src/lib.rs:95         gl::load_with(|s| window.get_proc_add
ress(s));

                                                             ^~~~~~~~~~~~~~~~~~~
~~~~~~~
C:\Users\xsmdesign03\.cargo\registry\src\github.com-0a35038f75765ae4\pistoncore-
glutin_window-0.16.0\src/lib.rs:95:27: 95:53 help: run `rustc --explain E0308` t
o see a detailed explanation
C:\Users\xsmdesign03\.cargo\registry\src\github.com-0a35038f75765ae4\pistoncore-
glutin_window-0.16.0\src/lib.rs:223:9: 223:48 error: mismatched types:
 expected `*const libc::types::common::c95::c_void`,
    found `*const ()`
(expected enum `libc::types::common::c95::c_void`,
    found ()) [E0308]
C:\Users\xsmdesign03\.cargo\registry\src\github.com-0a35038f75765ae4\pistoncore-
glutin_window-0.16.0\src/lib.rs:223         self.window.get_proc_address(proc_na
me)

                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

**Comment by mitchmindtree** [comment]
It looks like you're using an outdated version of `glutin_window` (in your log it says version 0.16.0, but [the latest](https://crates.io/crates/pistoncore-glutin_window) is 0.20.0) - Have you made sure you're using the latest versions of your deps in your Cargo.toml? Otherwise, have you tried `cargo update`?

**Comment by walkblank** [comment]
Thank you for you reply, you are right,   it's problem of the  outdated version of  dependencies.  i changed the required version of `piston-windows`  to the latest   "0.32.0"  ,   then try cargo build again ,  it download the latest version of `glutin_window`  0.20.0 automatically  and build successfully
