### ISSUE TITLE
Going on a small vacation

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1020]
Will be gone for a few days on a trip to west Norway to visit relatives. Currently, I've been learning more about computer assisted theorem proving this week, stepping down a bit on the pace of Piston, as I work best when focusing on a single project at a time. This will also save some duplicate work, since Gfx and Conrod are under redesign. Plans are ready for texture filtering in the piston-graphics backends, but since the Gfx design might require some redesigning in piston-graphics, it is not high priority (sorry to those who need nearest texture filtering to make pixelart games!).

Good news: I figured out a backward propagation mechanism in path semantics that allows expressions to use "normal programming". (path semantics is the investigation of an alternative paradigm to dependently types)

@mitchmindtree and @nwin have ownership, there are plenty of people in the admin group, so I expect things to run smoothly when I am gone.

**Comment by mitchmindtree** [comment]
Have a great journey chap :smile_cat: wish I was visiting Norway!

**Comment by bvssvni** [comment]
It was great!
