### ISSUE TITLE
An embeddable, auto-generated/updated interactive ecosystem DAG visualisation.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/piston#1022]
Original idea [in this reddit comment](https://en.reddit.com/r/rust/comments/3yx2fa/what_is_happening_2_piston/cyisab3).

Problem
-----------

One of the things newcomers find most frustrating is trying to work out the structure of the Piston ecosystem and how each of the crates relate to each-other. The wikis go a long way to help, though require a substantial amount of reading and memorisation to internalise. The dependency graphs also help, though are often very messy showing dev-dependencies and many non-piston crates.

Solution
-----------

It would be really nice to make a tool along the lines of the dependency graphs that already exist, but with a few more features:
- Limit node visibility to those crates whose Cargo.toml `repository` link leads to a repository within some given github user or organisation (in our case, PistonDevelopers).
- Greater edge distinction:
    - Solid lines for required dependencies.
    - Slightly faded, dotted lines for optional "feature" dependencies.
    - Small version number on the centre of each edge indicating which version is depended upon.
    - No lines for dev-dependencies. Perhaps the program can take some argument to toggle them on or off.
- A small amount of interactive info at each node, including:
    - Clickable crate name that links straight to the entry on crates.io
    - Travis build badge
    - crates.io version badge
    - crates.io license badge
    - Date and time of the latest commit
- The ability to highlight a particular crate, so that when displayed in the README of some repository, it displays the repository's position within the Piston ecosystem.
- Embeddable and automatically updated - perhaps using a little script that travis can run on the merge of a successful build? Could also be great to have this on the landing page of piston.rs.

I think having a clear, interactive visualisation like this would go a long way to help users to:
- immediately survey the ecosystem for projects that are relevant to them
- understand how their contributions will positively impact downstream projects
- get a brief insight into the maturity and usability of each project (version, date, license, build status)
- understand how backend trait crates (like graphics and window) relate to their implementations and in turn easily see exactly what options they have

I think something like this could really help piston to appear less fragmented, reduce common confusions and tie together the whole ecosystem in a single, simple visualisation.

**Comment by mitchmindtree** [comment]
Potential name for the project `eco-vis` short for "Ecosystem Visualisation".

**Comment by mitchmindtree** [comment]
Hah, just went onto twitter about 15 minutes after posting this and saw [this](https://twitter.com/czaplic/status/683077481725730816)! Similar concept, but not quite as extensive as the above feature list.

**Comment by bvssvni** [comment]
Is there anything the Elm community doesn't get right? :smile: 

I plan to do something else in the immediate near future. However, here are some ideas/thoughts:

- Could use dependency format from [Eco](https://github.com/PistonDevelopers/eco) or develop another format with piston-meta
- Should it be HTML/Javascript/Emscripten?
- Might suffer from "use once": High utility for new people, lower utility as you use it. The more efficient it is the less utility afterwards, which might make it difficult to prioritize.
- Could be useful as a more general tool for visualizing complex information? My mathematical mind is interested in key insights here, is there a higher learning rate than reading for example, measured by a stopwatch? Maybe some hidden assumptions here.
- How much will it cost to maintain per week? I tried to do an estimation, but it is tricky. Might be some hidden costs that are non-obvious now.
- Could create the repo and let see what people get interested in the project.

**Comment by bvssvni** [comment]
I think we should wait with this project until we've done with the planned redesigns. Closing for now.

**Comment by mitchmindtree** [comment]
No problem! What are the planned re-designs btw? Are you talking about the graphics related ones?

**Comment by bvssvni** [comment]
@mitchmindtree Yes, the graphics related ones.
