### ISSUE TITLE
Use `while let` in event loop

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1027]
See the comment https://github.com/PistonDevelopers/piston/issues/1026#issuecomment-169568288.

@mitchmindtree got the idea that you could use a `while let` instead of a `for` in the event loop.

Current design:

```Rust
for e in window.events() {
    ...
}
```

New design:

```Rust
let mut events = WindowEvents::new();
while let Some(e) = events.next(&mut window) {
    ...
}
```

This makes it unnecessary to take the window by value to the `WindowEvents` constructor. You do not have to use `Rc<RefCell<T>>` to share the window between two structures.

**Comment by bvssvni** [comment]
Some other changes we could make:

- [ ] Remove `EventMap`, since no application has used anything but `Event`.
- [ ] Remove `Events` trait
- [ ] Remove `EventLoop` trait, rename `WindowEvents` to `EventLoop`

**Comment by bvssvni** [comment]
The piston_window wrapper could be redesigned. Perhaps we could use it as a battery-included library that reexports other libraries?

**Comment by mitchmindtree** [comment]
Nice! I like the sound of all of these changes - especially the simplification of the event stuff :smile_cat: 

Maybe one idea for the new design above would be to change
```rust
let mut events = WindowEvents::new();
```
to
```rust
let mut events = window.events();
```
just to save the user one less import?

> The piston_window wrapper could be redesigned. Perhaps we could use it as a battery-included library that reexports other libraries?

I'm curious as to what you mean by this? It sounds a lot like how piston_window already works?

**Comment by bvssvni** [comment]
@mitchmindtree I was thinking about making it even easier to get started with Conrod and such. Nevermind, I'll need some more time to think it through. Let's focus on this change first.

**Comment by bvssvni** [comment]
I decided to keep `Events` and `EventLoop` to save the user one less import, and since `PistonWindow` in the piston_window crate implements `EventLoop`.

**Comment by bvssvni** [comment]
You still have to import `Events`, though, because event_loop depends on the window crate. Can't add another method without adding a trait.

**Comment by bvssvni** [comment]
One idea is to remove `Events` trait and rename `WindowEvents` to `Events`:

```Rust
let mut events = Events::new();
while let Some(e) = events.next(&mut window) {
    ...
}
```

However, when Rust get specialization it will be possible to change the default settings in a custom window backend if there is an `Events` trait.
