### ISSUE TITLE
Name ideas for a rusty dynamically typed scripting language

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1029]
The past days I've been working on a scripting language for fun: https://gist.github.com/bvssvni/c473c82242b1460a6741

It's a mix of Rust, Go and JavaScript.

- Just developed for fun right now
- Using [Piston-Meta](https://github.com/pistondevelopers/meta) for parsing, so people can change the syntax without recompiling
- Goal: To develop a scripting language that is ordinary - specifically avoiding weird or fancy stuff
- Does not use a garbage collector yet - uses lots of `.clone()` though and can unsafely return local variables inside objects
- Go like `for i := 0; i < n; i += 1 { ... }` loops and `:=` for variable initialization and `=` for mutable assignment
- Dynamically typed, similar to Javascript: Arrays `[1, 2, 3]` and objects `{x: 0, y: 0}` (however, `=` expects same type)
- Function declaration similar to Rust: `fn foo() -> { ... }` for functions that returns a value and `fn foo() { ... }` for functions that does not return a value
- Variable name shadowing like in Rust

**Comment by bvssvni** [comment]
Some ideas for naming:

- DynamoScript
- Rustus
- Sneik

**Comment by bvssvni** [comment]
I know this language is supposed to be an ordinary scripting language, but since I'm also researching path semantics I found a way to express design-by-contract for dynamically typed scripting languages https://github.com/bvssvni/path_semantics/wiki/Dynamic-Path-Semantics. However, the notation is ambiguous with array indexing, so it needs some rethinking.

**Comment by tillarnold** [comment]
I like DynamoScript. It fits with the Industrial theme that the rust language as well as the piston project has (cargo, crate, servo, turbine, conrod). I'm curious, what's the idea behind Sneik?

**Comment by tillarnold** [comment]
What about ThrustScript (or just thrust)? The word "rust" is in there, it fits with the Industrial theme. And it sounds like trust, which would fit the design-by-contract feature. (by the way all this path semantics stuff sounds very interesting, even doe I don't really fully understand it)

**Comment by bvssvni** [comment]
Thrust is very nice :smile:

**Comment by viperscape** [comment]
I'm partial to Dust, dynamic rust. Rust is begging for a cool dynamic language. Curious though, how do you plan on implementing this if rust is static compiled? I was hoping to create a dynamic language but realized rust could use a jit, and rust interoperability would be heavy handed unless made automatic with some macro ffi generator.

**Comment by bvssvni** [comment]
@tillarnold Here is a diagram that might explain it better:

```
x --------- f[g](g(x))
|              |
|              == check for equality
|              |
f(x) ------ g(f(x))
```

In normal programs, you compute `x` and then `f(x)`. Dynamic path semantics is an additional branch of computation that checks for equality. This can be used to discover logical errors.

For example, when appending two lists, you can check that their length is the sum of the inputs. If not, then there is something wrong and the program is stopped.

I have not implemented this yet and do not plan to do so in the short term. However, this is an idea we could explore later if we work on our own scripting language.

**Comment by bvssvni** [comment]
The idea behind "Sneik" was the two first letters are my initials, and I wanted something unique. However, my current favorite now is Thrust.

"Dust" in norwegian means "idiot", so I like Thrust better.

**Comment by bvssvni** [comment]
Currently, the runtime uses a stack `Vec<Variable>`.

```rust
pub enum Variable {
    Return,
    Bool(bool),
    F64(f64),
    Text(Arc<String>),
    Object(Object),
    Array(Vec<Variable>),
    Ref(usize),
    UnsafeRef(*mut Variable),
}
```

`UnsafeRef` is only used in left expression when assigning or mutating a value, eg. `x.a := 2`. This is safe because it is evaluated after the right hand expression.

`Ref` is only used to refer to other data on the stack. When a reference is assigned the lifetime checker complains if it does not outlive the object it is assigned to.

The lifetime checker runs directly on the meta data parsed by piston-meta in parallel with the construction of the AST. Then, if the program passes the lifetime check it creates a runtime and executes by walking the AST.

The runtime works, and I am working on the lifetime checker. So far:

```
    1113 src/ast.rs
      44 src/lib.rs
     636 src/lifetime.rs
    1031 src/runtime.rs
    2824 total
```

In additon there is about 100 loc of meta syntax that defines the grammar. This can be changed without recompiling.

One thing we could do later is to generate Rust code, using `Vec<Variable>` as stack.

**Comment by bvssvni** [comment]
Unfortunately Thrust is taken on crates.io.

**Comment by bvssvni** [comment]
We'll use Dynamo! The repo is https://github.com/PistonDevelopers/dynamo.
