### ISSUE TITLE
ld: cannot find -lfreetype

### ISSUE THREAD

**Issue by philippotto** [PistonDevelopers/piston#1033]
When trying to compile my project which depends on piston, I get the error message:
`ld: cannot find -lfreetype`. I'm using Windows 10 with mingw.

I followed the README at https://github.com/PistonDevelopers/freetype-sys, but still get the error. I tried the -pc-windows-gnu as well as the -pc-windows-msvc part, but neither did work.

I know that almost the same issue was raised in #969, but since @TheRealHnefi didn't respond to my comment and I cannot reopen his issue, I thought I'd create a new one.

**Comment by pangshaoqiang** [comment]
Try this method:
Get the freetype.dll from [https://github.com/PistonDevelopers/binaries](https://github.com/PistonDevelopers/binaries) and copy it to `...(your rust path)\lib\rustlib\x86_64-pc-windows-gnu\lib`.

**Comment by philippotto** [comment]
This solved my issue. Thank you!

**Comment by mrZalli** [comment]
Thanks to this I was I was finally able to make the starting example to compile.
When I run it however it only shows a frozen window with a white background that prints `[0x7FED92BAAA0] ANOMALY: meaningless REX prefix used` to std out and stays on for a while after trying to shut it down from the task manager.
