### ISSUE TITLE
Going on vacation

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1040]
The latest Gfx redesign has been the most complicated upgrade so far, but I think it has been worth it.

We have finally got fixed the color space issues in gfx_graphics, so piston_window 0.37.0 should work. Still, there is a lot work to do, and the ecosystem is not in the shape I hoped it would be.

However, now I definitely need a break, and it's the winter holiday where I live. Will be back in a week!

**Comment by mitchmindtree** [comment]
Thanks for your work on adapting to the latest gfx updates @bvssvni! Enjoy your well-deserved break :+1:

**Comment by gaudecker** [comment]
Have a nice vacation! :heart:

**Comment by bvssvni** [comment]
It was nice!
