### ISSUE TITLE
README: link to "event" is dead

### ISSUE THREAD

**Issue by remram44** [PistonDevelopers/piston#1045]

**Comment by bvssvni** [comment]
The repo was deprecated and moved to https://github.com/PistonDevelopers/piston/tree/master/src/input. Is there a dead link somewhere?

**Comment by remram44** [comment]
The deadlink is right there in `src/input/README.md`:
```markdown
For generic event programming, use [event](https://github.com/pistondevelopers/event).
```

**Comment by bvssvni** [comment]
Thanks! The event library was merged with the input library. Closed by https://github.com/PistonDevelopers/piston/pull/1046.
