### ISSUE TITLE
Rename `Joystick` to `Controller`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1047]
See https://github.com/PistonDevelopers/piston/issues/884#issuecomment-197892776

The name "joystick" is old and everyone uses "gamepad" nowadays.

However, "controller" is a more generic and suitable name.

**Comment by crazymykl** [comment]
It depends on the genre. You don't play a flight sim with a "gamepad".

Perhaps `GameController` as a general term?

**Comment by bvssvni** [comment]
Alternatives:

- `PlayerDevice`
- `GameDevice`

**Comment by luser** [comment]
`Controller` or `GameController` are pretty sensible. There's good precedent here with SDL 2 having GameController APIs: https://wiki.libsdl.org/CategoryGameController

The XInput documentation refers to them as "Controller" basically everywhere:
https://msdn.microsoft.com/en-us/library/windows/desktop/ee417001(v=vs.85).aspx

although the actual struct for getting data out of an XInput device is `XINPUT_GAMEPAD`:
https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.reference.xinput_gamepad(v=vs.85).aspx

The Linux kernel does still call them "joysticks", and has a `joydev` driver, but I wouldn't use that anyway nowadays, the `evdev` driver is better (although they still get called "joysticks" there, but Linux is very 1990s):
https://www.kernel.org/doc/Documentation/input/input.txt

SDL 2 uses evdev on Linux:
http://hg.libsdl.org/SDL/file/a18c12b02b69/src/joystick/linux/SDL_sysjoystick.c

The OS X/iOS/tvOS docs call them "Game Controllers":
https://developer.apple.com/library/ios/documentation/ServicesDiscovery/Conceptual/GameControllerPG/Introduction/Introduction.html

The Android docs also call them "Game Controllers":
http://developer.android.com/training/game-controllers/index.html

and internally will discriminate between `SOURCE_GAMEPAD` and `SOURCE_JOYSTICK`, although I don't know that I've ever seen anything do the latter in practice:
http://developer.android.com/reference/android/view/InputDevice.html#SOURCE_GAMEPAD
http://developer.android.com/reference/android/view/InputDevice.html#SOURCE_JOYSTICK

**Comment by bvssvni** [comment]
"Controller" sounds simple and nice.
