### ISSUE TITLE
Requesting feedback for Piston Window Guide

### ISSUE THREAD

**Issue by Phlosioneer** [PistonDevelopers/piston#1071]
src/window/User\ Guide.md latest version of #1068 

Looking for comments on style, on content, and on topics or details that could be added.

**Comment by Phlosioneer** [comment]
Thanks @bvssvni for all the feedback! I'll push a new commit tonight fixing all the things you pointed out, and leave the ones we're still discussing.

**Comment by bvssvni** [comment]
Alright! I might be hacking on some details today and tomorrow. Use `git pull --rebase PistonDevelopers master` if there is a merge conflict.

**Comment by Phlosioneer** [comment]
Will-do.

**Comment by bvssvni** [comment]
I added a milestone for the v0.23 version. My goal is to release a new version tomorrow. It would be nice to have made some improvement to the docs!
