### ISSUE TITLE
Add `fullscreen_on_f11` to `WindowSettings`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1075]
It would be nice to toggle fullscreen on/off for prototyping.

Need to test the interaction with re-creation of OpenGL context.

**Comment by getynge** [comment]
So to clarify, this would add a toggle fullscreen_on_f1 to struct WindowSettings, and would add some functionality that listens for a button press?

If so then I have a question, where does Piston normally handle window input?

**Comment by bvssvni** [comment]
Yes, the window would listen for F1 presses and toggle the fullscreen mode on/off.

**Comment by getynge** [comment]
Alright, I'm very new to this project and want to be sure I'm writing code in the appropriate style.

Would it be alright to intercept input from release.rs?  Or would it be better to handle it from the event loop?

**Comment by bvssvni** [comment]
I think it should go in the window backend, when polling events.

**Comment by getynge** [comment]
Alright then, so just to be sure:

As far as piston goes, I am simply adding a toggle fullscreen_on_f1 and add the appropriate getters and setters to the AdvancedWindow trait.

Then in terms of implementation, actual handling of f1 presses would go to backends such as piston_window, pistoncore-glutin_window, etc...

If I understand correctly then I'll go ahead and do that.
(sorry about all of the questions, this is the first project I've ever contributed to and this is my first contribution)

**Comment by bvssvni** [comment]
OK, you got it!

**Comment by bvssvni** [comment]
We'll still have to test it with at least one window backend, so just open up a PR when you are ready and I'll help from there.

**Comment by getynge** [comment]
Alright, I'll go ahead and do a quick write-in.  Should I also write a simple implementation in one of the backends?

**Comment by bvssvni** [comment]
Sure, if you get to it. You can override a dependency locally with Cargo, see https://github.com/PistonDevelopers/piston/issues/482.

**Comment by getynge** [comment]
So I've begun implementing the changes in my fork of the glutin-backend.  I've managed to get intercepting the button press working, although glutin does not support making an existing window fullscreen without destroying the existing window and creating a new one with (almost) identical settings.

I can solve this by keeping a copy of the window settings in GlutinWindow and rebuilding the window from those settings when f1 is pressed, would this be a good approach to the problem?

**Comment by bvssvni** [comment]
Yes, that would be acceptable. The title and size should be overridden by the current window. It would be nice if it remembered the position when going from fullscreen to window. I hope this works with OpenGL objects etc.

For the window backends that uses alternatives to build a window, `Option<WindowSettings>` could be used.

This feature is meant to be used for prototyping and editors where you have multiple windows, where you can hit F1 to make one window fullscreen, test the gameplay and then go back to the editor mode. The point is to reduce the amount of coding to get this functionality.

**Comment by getynge** [comment]
I have fullscreen _sortof_ working with the glutin window backend.

Current issues I have yet to nail down:

* After switching the context the frames stop updating
* When resizing the window (on Mac) the old window that should be destroyed is not
* On Mac, both the new and the old window respond to input, and only the original window has functional decorations.

I have not been able to confirm how my changes work on Windows, but these are the problems I have to nail down based on what I've seen from Linux and Mac.

**Comment by ForsakenHarmony** [comment]
I think it should be F11 because that's somewhat of a standard

**Comment by bvssvni** [comment]
@ForsakenHarmony I agree! Changed the title.

**Comment by bvssvni** [comment]
Closing as outdated. Feel free to open up a new issue.
