### ISSUE TITLE
How should I test piston when using piston-window?

### ISSUE THREAD

**Issue by getynge** [PistonDevelopers/piston#1081]
If I am trying to test changes to piston, should I list piston-window as a cargo dependency or should I modify a local version of piston-window to use my modified version of piston as a dependency?

My only worry is that if I use the vanilla piston-window as a dependency, the release version of piston would end up getting used and thus I would not actually be testing any changes I make to piston.

**Comment by bvssvni** [comment]
You can override dependencies locally. See https://github.com/PistonDevelopers/piston/issues/482

**Comment by getynge** [comment]
Ah, thank you for the clarification.
