### ISSUE TITLE
Sized vs not-Sized?

### ISSUE THREAD

**Issue by Phlosioneer** [PistonDevelopers/piston#1083]
I notice that the Advanced window trait requires Sized, while the Window trait doesn't. Why is that?

**Comment by bvssvni** [comment]
I forgot the reason, but think it has something to do with pre-1.0 rules for constraints. It was in the original proposal https://github.com/PistonDevelopers/window/issues/46, so I think we can remove it.

**Comment by bvssvni** [comment]
Ah! Here is why: The chaining methods requires `Size`.

**Comment by Phlosioneer** [comment]
Ah, that makes sense.
