### ISSUE TITLE
Request for more blog posts

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1102]
Feedback on /r/rust: https://www.reddit.com/r/rust/comments/4sc0wg/dyon_08_is_released_piston/d58aoy4

Posting blogs: https://github.com/pistondevelopers/blog.piston.rs

Show people what has happened in the project you work on!

**Comment by bvssvni** [comment]
I fear people will snap if I post more Dyon blog posts :P

I plan to post about the upgrading nightmare due to newer lower level graphic APIs like Vulkan and DirectX 12. This required a complete different thinking and I'm glad I had other projects like Dyon to fall back to. This is finally coming to an end now that the ecosystem is almost entirely upgraded.

Otherwise, I saw @mitchmindtree is experimenting a lot with Conrod, and would like to see a blog post about this 🙏 🐹 . There have been some big design challenges that seem interesting for people not familiar with the challenges of UI frameworks.

**Comment by echochamber** [comment]
I don't really have anything to write about currently, but if anybody wants a proofread/review of their blogpost before posting it I'd be happy to offer to help in that capacity.

**Comment by bvssvni** [comment]
Closing for now.
