### ISSUE TITLE
Alternative event loop

### ISSUE THREAD

**Issue by christolliday** [PistonDevelopers/piston#1109]
I'm interested in using Piston, specifically as a backend for Conrod, but with an event loop based on waiting for events rather than polling. The standard Piston event loop makes sense for a game engine but not necessarily a lightweight GUI app. So, would it be within the scope of Piston to modularize the event loop so that an app can supply a custom event loop, or alternatively modify the existing event loop so that continuous polling can be toggled on and off? I lean more towards the pluggable event loop, to avoid breaking/overcomplicating the existing event loop.

I can imagine, outside of just static UI apps, that there are other use cases for using Piston that would benefit from a non fixed rate event loop, eg. graphics visualisation, puzzle games etc.

The basic design I'm thinking right now would be, change WindowEvents from a struct to a trait, and add an alternative constructor for the window backends that can take a WindowEvents implementation.

Alternatively, the event loop could be separated from the Window entirely, so that an app could instantiate it's own event loop, and feed events back to the Window. This could make it easier to use multiple Windows with one event loop.

For the specific event loop I am using, it also requires adding a `wait_event` method to the Window trait, which is equivalent to `poll_event` but is blocking.

I've got an non-polling event loop working on forked versions of Piston, piston_window and glutin_window, but the code is mostly hacked together. If this feature makes sense for Piston I could clean it up and make pull requests for those three repositories.

**Comment by bvssvni** [comment]
The piston_window crate is not meant to be depended on by other libraries. I don't know why Conrod is depending on it, but my guess is lack of abstraction for bridging window + 2D graphics.

The event loop is designed to be replaced by alternatives when needed when used directly from the Piston core.

**Comment by christolliday** [comment]
The piston_window crate isn't depended on by Conrod the library, just by the example applications in Conrod.

Thanks for clearing that up, I can see that the event loop is independent except in piston_window.

In that case, it sounds like it makes the most sense for Conrod to provide it's own version of piston_window with it's own event loop, that can be used in examples, instead of making piston_window event loop agnostic, does that sound right?

So the only change that needs to be made to Piston to support a waiting loop is just adding a `wait_event` method to the piston core Window trait, alongside `poll_event`. I could implement it for glutin_window, with unimplemented!() on the other backends, is that ok?

**Comment by bvssvni** [comment]
Can `IdleEvent` be used?

**Comment by christolliday** [comment]
Not as far as I know, unless I'm missing something. `wait_event` would be used to block the main thread until an input event happens, rather than the sleep, wake up, poll cycle. 

It might even be useful to optimize the standard fixed rate event loop. For instance rather than sleeping until the end of the frame length, handling all input events, then updating, you could wait for input and handle input events as soon as they happen, but if none occur, have a second thread wake up the first to post an update event. It could prevent a situation where the update is overly delayed by a backlog of input events. This may or may not ever be a problem, but it's good to have the functionality available regardless for other event loops, and I would guess all backends should support it.

**Comment by christolliday** [comment]
Although, actually I suppose I can just add it to glutin_window for now, and if it is added to other backends in the future then it can be added to the Window trait
