### ISSUE TITLE
Nearest texture filtering doesn't work

### ISSUE THREAD

**Issue by VelocityRa** [PistonDevelopers/piston#1115]
I can't get nearest texture filtering to work. I want sharp edges, but despite me setting the texture
with the relevant settings: ![](http://image.prntscr.com/image/446d060b68be4fb1a4dae0e5d6c3e8ac.png), I get blurry edges when rendering while scaling the Transform like so: ![](http://image.prntscr.com/image/617a975f714546148e0fd8f1ca6e91fb.png). 

Here's how I initialize the Image in case it's relevant:
![](http://image.prntscr.com/image/5e342c1ac1544c68bad32d65fa826883.png)

Or am I not supposed to scale it like that?

[Here](http://image.prntscr.com/image/8278ca8854514757b112765b808300de.png)'s the output (the white randomly placed pixels aren't suppossed to be blurry, but sharp.

All the code is here in case you need to take a look: https://github.com/VelocityRa/rustboy
This was tested in the latest version of every package used, locally.

**Comment by bvssvni** [comment]
Seems the filter settings are ignored https://github.com/PistonDevelopers/gfx_texture/blob/master/src/lib.rs#L125-L131

**Comment by VelocityRa** [comment]
Yup... weird that it hasn't been reported before.

So, `create_texture_const_u8` doesn't accept [gfx::tex::FilterMethod](http://docs.piston.rs/piston_window/gfx/tex/enum.FilterMethod.html), how are we supposed to set it? There isn't another method that does, too unless I missed something.

**Comment by VelocityRa** [comment]
Nevermind, it seems like this info is stored in [gfx::tex::SamplerInfo](http://docs.piston.rs/piston_window/gfx/tex/struct.SamplerInfo.html) in gfx.

**Comment by Eroc33** [comment]
It looks like currently `Gfx2d` has one unchangeable sampler per instance, but given the `Texture` api it seems like each `Texture` should contain a sampler (or an optional sampler and a default in `Gfx2d`), since that seems to be the only way to have a per texture filter.

**Comment by VelocityRa** [comment]
@Eroc33 Yeah exactly, but I remember looking a bit at the gfx calls available and I wasn't able to figure out how to change the texture's sampler when instantiating it from the factory.

**Comment by Eroc33** [comment]
@VelocityRa that's my point. You can't bind a sampler to a texture in gfx, you have to have both when you issue a draw call

**Comment by VelocityRa** [comment]
Ah, I see.
So right now we basically can't have textures with different filter methods render at the same time? That seems... less than ideal.
Here's where the sampler is created, I think: https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L283-287

**Comment by VelocityRa** [comment]
Hm, take a look at this: https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L556
(`tri_list_uv` is used for drawing)
Maybe we could provide it with a different sampler depending on the `texture`?
Unless we can somehow do it by changing `Resources::new` that I posted above. But we can't do it from there right? We don't have access to the texture from there.

**Comment by Eroc33** [comment]
It looks like whatever we do here there's may have to be significant changes across several of the piston crates to add this. I'm thinking either we should add a sampler field to texture, or make it a tuple of `(Texture,Sampler)` (the tuple representation is even use in tri_list_uv here: https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L556 )

**Comment by VelocityRa** [comment]
Yeah that's why I wasn't sure what to do, I was wondering if I was missing an obvious solution but apparently not.
Adding an `Option<Sampler>` field to `Texture` with a fallback to the default sampler might be the best solution. What do you think? I have some time, I could try implementing that now.

**Comment by Eroc33** [comment]
Actually I'm not sure when you would ever have `None` in the `Option<Sampler>`, unless you made a special case for whatever the default filter is, but that seems prone to breakage. If you do see a situation you could actually have `None` in then go for `Option<Sampler>`, but I suspect just `Sampler` makes more sense here.

**Comment by VelocityRa** [comment]
Actually I suggest None is the default value, because I don't want to change the constructor. That's why I want it to be an Option, so that specifiying the sampler info is optional (through a setter). Default behaviour would be to use `sampler` like it does now (billinear filtering and clamp warp mode).
I'd make it an optional parameter or something like that, but again, Rust doesn't support that.
Other than the setter there could also be an altenative constructor with the sampler included, but even that might not be needed.

**Comment by VelocityRa** [comment]
Awesome, this commit https://github.com/PistonDevelopers/gfx_texture/commit/5a0560233a209292fe076b2cd27b7e11603111e9 fixed this. I can close this now.
