### ISSUE TITLE
Build fail with library being linked to more than one version of the same package

### ISSUE THREAD

**Issue by rcastill** [PistonDevelopers/piston#1151]
Hi,

Trying to get started, I used the example in the `README.md` by having the following as my only dependency:

```toml
[dependencies]
piston_window="0.61.0"
```

When I run `cargo build` it fails:
```
error: native library `CoreFoundation.framework` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  core-foundation-sys v0.2.3
  core-foundation-sys v0.3.0
```

I'm working on macOS 10.12.3 if it is useful to know anyhow.

Thanks in advance!

**Comment by bvssvni** [comment]
There was a similar problem [here](https://github.com/PistonDevelopers/rusty-tetris/issues/5). Try `cargo update`.

**Comment by rcastill** [comment]
It did not work :c

**Comment by bvssvni** [comment]
You can try adding sdl2_window https://crates.io/crates/pistoncore-sdl2_window/0.39.0 to Cargo.toml, then change your code to this:

```rust
extern crate piston_window;
extern crate sdl2_window;

use piston_window::*;
use sdl2_window::Sdl2Window;

fn main() {
    let mut window: PistonWindow<Sdl2Window> = ...;
    ...
}
```

**Comment by rcastill** [comment]
It didn't work either

**Comment by bvssvni** [comment]
I think I know why. Try the tutorial instead, but replace "glutin_window" with "sdl2_window" 0.39.0 https://github.com/PistonDevelopers/Piston-Tutorials/tree/master/getting-started. This uses opengl_graphics with the Piston core, so you won't run into problems with the Glutin window backend.

**Comment by rcastill** [comment]
This one works. Is the backend the only change? or should I consider different approaches in implementation?

Thanks for your help!

**Comment by bvssvni** [comment]
For 2D, there is not much change, but piston_window uses Gfx for 3D.

**Comment by bvssvni** [comment]
This should be fixed now. Use `cargo update`. Closing.

**Comment by rcastill** [comment]
I can confirm that!
