### ISSUE TITLE
`decorated` and `resizable` do not work in Debian/Gnome shell/wayland

### ISSUE THREAD

**Issue by Boiethios** [PistonDevelopers/piston#1157]
```
$ uname -a
Linux *** 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux
```

with `GNOME 3.22.2` using `wayland`.

I tried the example:

```
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow =
        WindowSettings::new("Hello Piston!", [640, 480])
		.exit_on_esc(true).decorated(true).resizable(true).build().unwrap();
    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform, g);
        });
    }
}
```

My window is not decorated, and I cannot resize it.

I tried in a gnome session using X11, and there were no issue: the window was decorated and resizable.

**Comment by Boiethios** [comment]
I am upping this issue because 4 months after my first message, wayland is still not fully supported. I tried the last `piston_window` version (`0.65.0`), and the window is not decorated nor resizable. Maybe I could help for this issue, but I have no idea how.

Can someone give me more information?

**Comment by bvssvni** [comment]
Have you tried swapping the backend?

Piston-Window uses Glutin by default, but you can change it by writing e.g.:

```
PistonWindow<Sdl2Window>
```

**Comment by Boiethios** [comment]
Works perfectly, thank you. Sorry for the misunderstanding: as I understand now, this is a glutin problem, not piston.

Maybe this could be highlignted in the main README?
