### ISSUE TITLE
Time-stamped input

### ISSUE THREAD

**Issue by ishitatsuyuki** [PistonDevelopers/piston#1158]
We cannot count too much on a fast event loop.

Instead, OS provides input events with timestamp, for example Linux evdev. It would be good to gain access to them through the input library.

**Comment by bvssvni** [comment]
In the case a window backend can not provide time stamps from the OS, it could produce them manually.

One special case is the update event, which perhaps not should have a time stamp to allow event transformation.

**Comment by bvssvni** [comment]
We could put time stamp on the events that are provided by SDL2.

Alternative, we could use a trait with a method that returns `Option<timestamp>`.
