### ISSUE TITLE
Automatically resize window on fullscreen

### ISSUE THREAD

**Issue by adiba** [PistonDevelopers/piston#1167]
When creating a new window with fixed size and fullscreen enabled, the _screen_ resolution gets changed (at least in Windows)...
Would it possible to automatically resize the window to match the screen resolution?
I haven't found a way to get the resolution of the current screen.

**Comment by bvssvni** [comment]
You can get the resolution of the current screen through Glutin/SDL2/GLFW.

**Comment by bvssvni** [comment]
Closing.
