### ISSUE TITLE
cannot open input file 'SDL2.lib'

### ISSUE THREAD

**Issue by erdog** [PistonDevelopers/piston#1171]
Hi Guys,

I'm trying to run the cube.rs example on Windows 10. The 2d examples work, but for the cube.rs I'm getting the following:

error: linking with `link.exe` failed: exit code: 1181
note: LINK : fatal error LNK1181: cannot open input file 'SDL2.lib'

Seems to be an issue with the sdl2_window crate.

I tried downloading the SDL2.lib and dll and dropping them into one of the lib paths; however, it still fails to run.

Any ideas?

Thanks!

**Comment by bvssvni** [comment]
There are some installing instructions for SDL2 in the README here: https://github.com/AngryLawyer/rust-sdl2

**Comment by erdog** [comment]
Great thanks, that worked!
