### ISSUE TITLE
Drop rustc-serialize dependency in pistoncore-input

### ISSUE THREAD

**Issue by dtolnay** [PistonDevelopers/piston#1173]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before making this happen?

**Comment by bvssvni** [comment]
We could move to Serde first, and then after a while drop rustc-serialize.

**Comment by bvssvni** [comment]
I think we should try dropping rustc-serialize and see how it goes.
