### ISSUE TITLE
Using piston with an ECS

### ISSUE THREAD

**Issue by torkleyy** [PistonDevelopers/piston#1180]
I'd like to add a chapter to Spec's book which gives a few hints how to use Piston and Specs together. The problem is the way the event queue works:

```rust
while let Some(event) = events.poll(&mut window) {
    if let Some(args) = event.input_args() {
        // Input
    }

    if let Some(args) = event.render_args() {
        // Render
    }
}
```

(Not sure if the above code is correct, I copied it from a question somebody asked on Gitter)

Is it okay to just recommend executing the systems in the `event.render_args()` if-let?

**Comment by bvssvni** [comment]
You should probably use `event.update_args()`.

**Comment by torkleyy** [comment]
Thanks for your help!
