### ISSUE TITLE
Piston's support and PR sucks

### ISSUE THREAD

**Issue by icefoxen** [PistonDevelopers/piston#1184]
The forum is a joke, there's nothing there but wacko posts on irrelevant stuff by one person.  You'd be better getting rid of it so nobody stumbles into it and gets the wrong idea.

There is no gitter and nobody from Piston ever hangs out on the #rust-gamedev IRC channel on Mozilla's network, so no newbies ever have a place to get first-hand help.  This is somewhat shameful for a major Rust project, given how many people have gone into various Rust IRC channel's and gotten fantastic help; that trains people to have high expectations.  The results of this is that newbies always wander into #rust-gamedev and ask for help and get told "don't use Piston because nobody there cares".

The Twitter is not terrible, I confess.

**Comment by bvssvni** [comment]
The forum is used by people for mostly offtopic discussion since the issue tracker is used for tracking stuff on projects. We will work on improving the help for new people, but the best way of getting it now is to open issues.

I don't usually hang out on #rust-gamedev because I already use too many forums and need to prioritize my attention on the right tasks. Please open issues.

**Comment by icefoxen** [comment]
Okay I'll just tell everyone with a Piston problem in #rust-gamedev to open an issue.

**Comment by icefoxen** [comment]
...though if the forum is off topic, then it shouldn't be listed as a place to start discussions. As it is, a new user (ie me, a year ago) will go to the forum, see nothing at all about Piston, Rust, or gamedev at all, and say "well I guess this project is irrelevant" and "this is the best the rust gamedev scene has to offer?"

It looks very unprofessional when a project's official forum has the last post about that project over a year ago.

**Comment by bvssvni** [comment]
It's a good idea to post more official posts on the forum. At the moment we are using the blog for this http://blog.piston.rs/.

I think we can open up individual issues for the relevant topics. So I will close this.
