### ISSUE TITLE
Your detractors are assholes

### ISSUE THREAD

**Issue by icefoxen** [PistonDevelopers/piston#1185]
Not an issue with you, though. Sorry and thanks for putting up with my shit. I'll try harder to keep my criticism to the constructive sort... Again.

I will probably fail, but I'll try to vent my spleen in pull requests rather than Reddit posts.

**Comment by bvssvni** [comment]
You show some symptoms of sleep deprivation. Please take care of yourself!

Notice that this a professional working environment and not a place for ranting. I'll close this issue since it distracting.

**Comment by bvssvni** [comment]
@icefoxen Some of your feedback has good points and I'm listening. You don't have to worry about me taking it personal or anything.

Sometimes I see people posting things telling that they are very anxious about the response. This is often a sign of lack of sleep, so it is best to tell people just in case. It is hard to know. Seems to happen a lot on the Internet.
