### ISSUE TITLE
Discussion about Render, AfterRender, Update, and Idle on input::Input

### ISSUE THREAD

**Issue by LaylConway** [PistonDevelopers/piston#1187]
These events in Input aren't actually input events, and window backends don't implement them. I think it may be beneficial to move them to a different enum and have a higher up enum like this:
```Rust
enum Event {
    Input(Input),
    Loop(Loop)
}
```
Alternatively this could be an option as well:
```Rust
enum Event {
    Input(Input),
    Render,
    AfterRender,
    Update,
    Idle
}
```
The arguments for doing this would be to make piston's generic window system more flexible for use outside piston itself, and to improve clarity on what window backends are supposed to give in terms of input events. It also would allow different approaches to be tested out with these higher-level loop events without breaking systems that depend on just the input events, and it would make it more clear when a library needs just the input events raised by a window backend, or also the loop events.

**Comment by bvssvni** [comment]
Notice that we did have this before but then merged them into the `Input` enum. See https://github.com/PistonDevelopers/piston/issues/1150. Perhaps we'll change it back.

**Comment by bvssvni** [comment]
I liked the idea of a `Loop` enum. It will make it possible to reuse code for event loops that doesn't use `Input`. For example, if you are using Piston without any window backend, but using e.g. Glutin, Winit, SDL2, Glfw or a native API directly.

It should be easier to convert back and forth between `E: GenericEvent`, `Input` and `Loop`. This can be done by adding `Into<Option<Input>>` and `Into<Option<Loop>>` as constraints on `GenericEvent`. It already has `From<Input>` so we should add `From<Loop>` as well.

**Comment by LaylConway** [comment]
:+1: The changes are looking good, this will make it a lot clearer what events an API is expected to raise.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston/pull/1194
