### ISSUE TITLE
I want to contribute to conrod

### ISSUE THREAD

**Issue by bobgates** [PistonDevelopers/piston#1190]
I'd like to work on the tutorial...

**Comment by mitchmindtree** [comment]
Hi @bobgates, that would be a great help! Please see the related issue at PistonDevelopers/conrod#505. Keep in mind that issue might be a little out of date, however that would be the best place to discuss it.

**Comment by bvssvni** [comment]
@bobgates Welcome to the team! I've sent you an invitation.

Closing this.
