### ISSUE TITLE
Add conversion from `[u64; 2]` and `(u64, u64)` to `Size`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1199]
See https://github.com/PistonDevelopers/piston_window/issues/200

**Comment by dowoncha** [comment]
I would like to take this. I have no problem implementing the From traits but is it safe to change the Size struct values from u32 to u64? There are no tests so I'm worried it could be a breaking change.

**Comment by bvssvni** [comment]
Oh, I didn't see the `Size` struct uses `u32`. I don't there is need for `u64`.

**Comment by bvssvni** [comment]
Closing since it supports `u32`.
