### ISSUE TITLE
Why does GlypheCache::new take a factory parameter `()`

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/piston#1210]
When updating to the latest version of Piston, I had to fix a called to `GlypheCache::new`. It looks like it takes in window factory. When I tried to pass in a window factory (similar to how some of the Piston examples pass one into a `Glyph` object, I got a compiler error.

It said that it was expecting `()`, which I thought was quite odd. Is this expected or a bug?

Here is the line in `rust-belt` where I had to pass in `()`:

https://github.com/johnthagen/rust-belt/blob/master/src/menu.rs#L185

```rust
        let mut glyph_cache = GlyphCache::new(
            "./assets/fonts/FiraSans-Regular.ttf",
            (),
            TextureSettings::new(),
        ).unwrap();
```

The example I referenced: https://github.com/PistonDevelopers/piston-examples/blob/master/src/hello_world.rs#L21

```rust
    let factory = window.factory.clone();
    let mut glyphs = Glyphs::new(font, factory, TextureSettings::new()).unwrap();
```

**Comment by bvssvni** [comment]
The `GlyphCache` is now generic and moved to Piston-Graphics.

It takes a `()` as factory parameter because opengl_graphics is the only backend that uses a global context.

**Comment by johnthagen** [comment]
Should I change how we use GlypheCache? Is there way the examples use Glyphe, better?

**Comment by bvssvni** [comment]
It should work the same. I plan to add more generic implementations later to Piston-Graphics that have different properties.

**Comment by johnthagen** [comment]
Thanks for the explanation.
