### ISSUE TITLE
Use the G2dTexture type in at least one example or tutorial

### ISSUE THREAD

**Issue by absurdhero** [PistonDevelopers/piston#1213]
Currently, the examples and tutorials never declare the specific type of a Texture. This means that new users will not know what type to use when declaring a reference to a Texture in their game.

All of the current sample code declares local variables like `let tex = Texture::from_path(...)`.  If a user is clever enough, they may figure out that this returns type `piston_window::Texture<gfx_device_gl::Resources>`. However, this is not the best thing to do since it requires importing the gfx_device_gl crate, creating dependency version skew and coupling the user's game to a specific gfx implementation. Some of the games showcased on the Piston website follow this practice.

Kvark on IRC pointed out that the correct practice is to use the `GfxTexture` type in the piston_window library which allows a level of indirection between the graphics backend and the application code.

**Comment by bvssvni** [comment]
This is a good idea!

**Comment by bvssvni** [comment]
I've opened a PR https://github.com/PistonDevelopers/piston-examples/pull/404

**Comment by bvssvni** [comment]
Closing.
