### ISSUE TITLE
First piston example don't work.

### ISSUE THREAD

**Issue by ghost** [PistonDevelopers/piston#1218]
When I try to run the first example in the main page it returns me an error after the screen pops up and closes it self ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn't find any pixel format that matches the criterias."', src\libcore\result.rs:906:4```, I search for it and find some people with the same problem, I runned the glutin first example and it works like a charm, I tryed to add the `.srgb(true)` and `.srgb(false)`, it don't work too;

Stack error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn't find any pixel format that matches the criterias."', src\libcore\result.rs:906:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at src\libstd\sys\windows\backtrace/mod.rs:65
             at src\libstd\sys_common/backtrace.rs:69
   1: std::panicking::default_hook::{{closure}}
             at src\libstd\sys_common/backtrace.rs:58
             at src\libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src\libstd/panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at src\libstd/panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:522
   6: rust_begin_unwind
             at src\libstd/panicking.rs:498
   7: core::panicking::panic_fmt
             at src\libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at C:\projects\rust\src\libcore/macros.rs:23
   9: <core::result::Result<T, E>>::unwrap
             at C:\projects\rust\src\libcore/result.rs:772
  10: game_test::main
             at src/main.rs:7
  11: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at src\libstd/panicking.rs:459
             at src\libstd/panic.rs:361
             at src\libstd/rt.rs:59
  13: main
  14: _tmainCRTStartup
  15: mainCRTStartup
  16: unit_addrs_search
```

Versions:
`rustc 1.22.1 (05e2e1c41 2017-11-22)`
`cargo 0.23.0 (61fa02415 2017-11-22)`
`piston_window = "0.70.0"`

My computer:
```
OS: Windows 7 Ultimate SP1 64 bits;
CPU: Intel Pentium Dual-CoreT4300 2.1GHz;
RAM: 3Gb;
GPU: Mobile Intel 4 Series Express Chipset Family;
VRAM: 1293Mb;
OpenGl version: 2.1;
DirectX version(I think it is irrevelant): 9, 10.0;
DirectX shader model: vs_4_0, ps_4_0;
Vulkan: Not available.
```

Code:
```
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow =
        WindowSettings::new("Hello Piston!", [640, 480])
        .exit_on_esc(true).srgb(false).build().unwrap(); //srgb
    while let Some(event) = window.next() {
        window.draw_2d(&event, |context, graphics| {
            clear([1.0; 4], graphics);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      context.transform,
                      graphics);
        });
    }
}
```

Note: Sorry about my english, I'm not fluent.

**Comment by pmarcelll** [comment]
The default OpenGL version for PistonWindow is OpenGL 3.2, but your GPU only supports OpenGL 2.1. You have to manually set the version to 2.1 by calling the `opengl(...)` method when you build the `WindowSettings`.

**Comment by bemeurer** [comment]
@pmarcelll Could you show how to do that? Also, is this documented somewhere? I feel like a rather large number of people don't have OpenGL 3.2 compatible hardware.

**Comment by pmarcelll** [comment]
@bemeurer I think it's documented on some methods, but not in the summary or on the builder methods. @celluloce showed the usage in the example.

OpenGL 3.2 is supported on anything AMD and Nvidia, it's also supported on Intel since Sandy Brigde, aka. second gen. Core i (except the Windows driver for Sandy Bridge only implements OpenGL 3.1 despite the complaint of many customers), and on every Intel Atom chip with an Intel IGP.

@celluloce The example doesn't work because you're also affected by #1202, it will be fixed when Mesa 18.0 is released (probably sometime next month).

**Comment by jonathandturner** [comment]
I'm seeing the same issue on a 7th gen Intel Dell XPS 13 running Ubuntu 17.10.  it could be the same Mesa issue as mentioned above.

**Comment by pmarcelll** [comment]
Arch Linux was updated to Mesa 18.0 recently, so I tested my Piston project and it works now. Ubuntu 18.04 will also ship with Mesa 18.0, so hopefully it won't be a problem much longer.

**Comment by C-Bouthoorn** [comment]
This seems to have been fixed with the latest `mesa 18.*`. See https://github.com/PistonDevelopers/piston/issues/1202 for more information.

**Comment by bvssvni** [comment]
Closing.
