### ISSUE TITLE
Drawing a line

### ISSUE THREAD

**Issue by iandanforth** [PistonDevelopers/piston#1224]
Hopefully this is a simple question. I'd like a function draw_line(a, b) that draws a line to the screen from a to b where a and b are points in the form [x, y].

The docs for Line do not contain examples and searches for this topic only turn up a pixel by pixel example. Any help or pointers would be appreciated.

**Comment by iandanforth** [comment]
Thank you very much! This works! Could you please tell me a bit about how you figured this out? I looked here: http://docs.piston.rs/mush/graphics/line/index.html and assumed that if you could call line() as a function it would show up under the list of functions just as rectangle() does. I'm very new to rust so I appreciate any tips on navigating/searching code in useful ways.

**Comment by iandanforth** [comment]
Ok I think I've found my point of confusion there exist (at least) two paths in the docs for line.

First result on google when you search for 'rust piston line' is:

http://docs.piston.rs/mush/graphics/line/index.html

Note the 'mush' part of the URL. These docs do NOT have a line function.

However there also exist this:

http://docs.piston.rs/graphics/graphics/line/index.html

These docs DO have a line function of the signature your example uses.

I'm not sure how to interpret this. Does 'mush' have a dependency on an alternate version of graphics?

**Comment by saraswathidatar** [comment]
I am trying to create a grid using graphics 2D library in piston. In order to draw a grid, function is defined as pub fn draw<G>(&self, line: &Line, draw_state: &DrawState, transform: Matrix2d, g: &mut G) where G: Graphics. I don't know what values to pass here. Any idea?

**Comment by inDigiNeous** [comment]
I'm having the same problem as @saraswathidatar , having trouble figuring out the proper type I must declare for the graphics type, i've tried many different things, I just want to make this function

```
fn draw_line_segment(color:[f32; 4], width:f64, interpolation:f64, p1:&Point2<f64>, p2:&Point2<f64>,
                     segment_width:f64, translation:Matrix2d, gfx: &mut Graphics) {
```

But I'm having trouble figuring out what the heck is the proper type for the Graphics that is coming from the draw_2d enclosure .. maybe you should add some examples to make it easier to create functions for beginners.

**Comment by bvssvni** [comment]
@inDigiNeous Try `&mut impl Graphics`. I added this to the FAQ: https://github.com/PistonDevelopers/piston/wiki/Frequently-Asked-Questions-(FAQ)#what-is-the-idiomatic-way-of-drawing-2d-for-generic-backends

**Comment by inDigiNeous** [comment]
Thank you @bvssvni, that works!

**Comment by bvssvni** [comment]
Closing issue.

**Comment by cata0309** [comment]
So how can I draw a simple line ? Your answers are not beginner friendly as you might consider !
