### ISSUE TITLE
Xbox One-compatible controllers events not firing

### ISSUE THREAD

**Issue by sophiajt** [PistonDevelopers/piston#1225]
Not sure how fleshed-out the controller/gamepad support is in Piston, yet.  I saw that you could receive the events.  While I was able to get key- and mouse-related events working, I wasn't able to see any of the controller events firing.

Just to be sure the device was working, I fired up Steam and it seems to be okay there.

Is this expected to work?  If so, are there additional setup steps?

This is on a Razer Wildcat, which is supported out of the box in Windows 10 as a Xbox One-style controller.

**Comment by bvssvni** [comment]
You probably need the pistoncore-sdl2_window backend.

**Comment by jonathandturner** [comment]
Ah! that makes sense.  So for the glutin backend to work, they'd need to add controller support to glutin, which piston would then expose.  Got it.

Would be great to be able to statically detect you're checking for an event type the current backend doesn't support.

**Comment by bvssvni** [comment]
Closing.
