### ISSUE TITLE
Does piston have support for setting mouse position?

### ISSUE THREAD

**Issue by GraemeWilde** [PistonDevelopers/piston#1229]
Hi,

This might not be the right place, but I wasn't really sure where to ask questions. I couldn't find anything in the docs about it, does piston support **setting** the position of the mouse?

**Comment by bvssvni** [comment]
The Piston core doesn't support it, but you can do it through the backend. E.g. `Sdl2Window` exposes the window handle https://docs.rs/pistoncore-sdl2_window/0.50.0/sdl2_window/struct.Sdl2Window.html#structfield.window

**Comment by GraemeWilde** [comment]
Thank you. Is this where I should ask any questions?

**Comment by bvssvni** [comment]
Yes.

**Comment by bvssvni** [comment]
Closing.
