### ISSUE TITLE
Is there a node/actor or actor component system for Piston?

### ISSUE THREAD

**Issue by Janonard** [PistonDevelopers/piston#1232]
Many/All game engines have an actor system where everything in the scene is represented by an actor: These actors can have other actors as children and the parent's transformations are also indirectly applied to the children too. Also, an actor can have so-called actor components with individual behavior which can be reused by other actors.

My question is now: Is there something like this in the Piston ecosystem? I mean, having such an actor system is one of the most important things for a gameplay programmer, so why isn't it implemented for Piston yet? Have I just missed it, is it only planned or do you consider this impractical?

If it isn't planned yet, what are your thoughts on how it should be? I have only dealt with a few engines, Unity and Unreal, which both have very varying implementations: In Unity, actors are only containers for components which you can create yourself, but in Unreal, they are more or less additions to individual actor classes. Which approach would be the best for Piston?

**Comment by bvssvni** [comment]
Piston is very modular and works with any actor/ECS system. https://crates.io/search?q=ecs

**Comment by Janonard** [comment]
Okay, thank you!
