### ISSUE TITLE
[HELP] Getting window size

### ISSUE THREAD

**Issue by AregevDev** [PistonDevelopers/piston#1241]
I am new to Piston, and during my collision check, I am having difficulties getting the size of the window
My window instance:
```
static mut WINDOW: Window = WindowSettings::new("piston", [640, 480])
    .opengl(OPEN_GL)
    .vsync(true)
    .exit_on_esc(true)
    .build()
    .unwrap();
```
My collision check:
```
if !(self.x + 150.0 < WINDOW.get_size().width as f64 && self.x > 0.0) {
            self.x_speed *= -1.0;
        }

        if !(self.y + 150.0 < WINDOW.get_size().height && self.y > 0.0) {
            self.y_speed *= -1.0;
        }

        self.x += self.x_speed * args.dt;
        self.y += self.y_speed * args.dt;
```
As I understand `WindowSettings` has a method `get_size` but I cannot reach it for some reason
Am I doing something wrong?

**Comment by bvssvni** [comment]
What's the compiler error?

**Comment by AregevDev** [comment]
```
error[E0599]: no method named `get_size` found for type `glutin_window::GlutinWindow` in the current scope
  --> src/main.rs:63:38
   |
63 |         if !(self.x + 150.0 < WINDOW.get_size().width as f64 && self.x > 0.0) {
   |                                      ^^^^^^^^

error[E0599]: no method named `get_size` found for type `glutin_window::GlutinWindow` in the current scope
  --> src/main.rs:67:38
   |
67 |         if !(self.y + 150.0 < WINDOW.get_size().height && self.y > 0.0) {
   |                                      ^^^^^^^^
```

There you go

**Comment by bvssvni** [comment]
It's `size`, not `get_size`.

**Comment by bvssvni** [comment]
https://docs.rs/pistoncore-window/0.32.0/window/trait.Window.html

**Comment by AregevDev** [comment]
error[E0599]: no method named `size` found for type `glutin_window::GlutinWindow` in the current scope
  --> src/main.rs:65:38
   |
65 |         if !(self.x + 150.0 < WINDOW.size().width as f64 && self.x > 0.0) {
   |                                      ^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
6  | use piston::window::Window;
   |

error[E0599]: no method named `size` found for type `glutin_window::GlutinWindow` in the current scope
  --> src/main.rs:69:38
   |
69 |         if !(self.y + 150.0 < WINDOW.size().height && self.y > 0.0) {
   |                                      ^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
6  | use piston::window::Window;
   |

Should I replace `glutin_window` with `piston::window`

**Comment by AregevDev** [comment]
If I am replacing `glutin_window::WindowSettings` with `piston::window::WindowSettings` I am getting this:
```
error[E0277]: the trait bound `piston::window::WindowSettings: piston::window::BuildFromWindowSettings` is not satisfied
  --> src/main.rs:20:6
   |
20 |     .build()
   |      ^^^^^ the trait `piston::window::BuildFromWindowSettings` is not implemented for `piston::window::WindowSettings`
```

**Comment by AregevDev** [comment]
Well, I moved to the `piston_window` crate instead of Glutin, but now I need to get the current window instance in the `update` method. I can not make `window` static because of the instance creation requires chain calling which is not supported by static variables, any idea? @bvssvni 

![image](https://user-images.githubusercontent.com/40574704/45832014-7334de00-bd09-11e8-8e5e-cfbf31d2bfd5.png)
![image](https://user-images.githubusercontent.com/40574704/45832030-7cbe4600-bd09-11e8-80d3-cc6eb971325a.png)

**Comment by AregevDev** [comment]
Any way I can access `window` from `update`?

**Comment by bvssvni** [comment]
Add what the compiler says: `use piston::window::Window;`.

**Comment by AregevDev** [comment]
```
error[E0277]: the size for values of type `dyn piston_window::Window` cannot be known at compilation time
  --> src/main.rs:14:9
   |
14 |     let mut window: Window = WindowSettings::new("piston", [640, 480]).opengl(open_gl)
   |         ^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `dyn piston_window::Window`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
   = note: all local variables must have a statically known size
   = help: unsized locals are gated as an unstable feature

error[E0277]: the size for values of type `dyn piston_window::Window` cannot be known at compilation time
  --> src/main.rs:18:10
   |
18 |         .unwrap();
   |          ^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `dyn piston_window::Window`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>

error[E0277]: the trait bound `dyn piston_window::Window: piston_window::BuildFromWindowSettings` is not satisfied
  --> src/main.rs:17:10
   |
17 |         .build()
   |          ^^^^^ the trait `piston_window::BuildFromWindowSettings` is not implemented for `dyn piston_window::Window`

error[E0277]: the size for values of type `dyn piston_window::Window` cannot be known at compilation time
  --> src/main.rs:29:32
   |
29 |     while let Some(e) = events.next(&mut window) {
   |                                ^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `dyn piston_window::Window`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>

error: aborting due to 4 previous errors
```
Size is unknown at compile time...

**Comment by bvssvni** [comment]
Replace:

```
let mut window: Window = ...
```

with:

```
let mut window: GlutinWindow = ...
```

**Comment by AregevDev** [comment]
Ok, I got the size working with `PistonWindow`, the only problem I have now is the scoping problem.

**Comment by bvssvni** [comment]
`static mut` got problems, should probably use https://github.com/pistondevelopers/current

**Comment by AregevDev** [comment]
Solved, I am OK now, thanks for your time and effort
