### ISSUE TITLE
Add Astra Terra to the list of games "Built with Piston"

### ISSUE THREAD

**Issue by christopherdumas** [PistonDevelopers/piston#1245]
Hi all, I can't find a GitHub repo for your website, so I'm just putting an issue here until someone can point me in the right direction to contribute to it.

I and a team of friends are working on a Piston-powered real-time strategy sci-fi game, *Astra Terra* with procedural worlds and a focus on story and simulation. Its powered by a goal-oriented AI, among other things. My team consists of an artist, myself (a programmer) and another programmer. We've been working on the game for about two years now, and have gotten quite far along. We plan on releasing it on Steam for about $10, so it doesn't have a GitHub repo (we use a private BitBucket), but [our website]( http://astraterra103026007.wordpress.com/) has a weekly blog. You can also find our design file (slightly incomplete) [here](https://docs.google.com/document/d/1gGrLvni32pu2j_6Q5PZhlbufTqZ8-OU8B0IL877ZrbY/edit?usp=sharing).

Let me know what you guys think about adding this to the piston.rs website.

**Comment by bvssvni** [comment]
The link to the blog is broken.

**Comment by christopherdumas** [comment]
Yes, my apologies. I’ve moved the website to
http://christopherdumas.org/astraterra

**Comment by bvssvni** [comment]
I added it to the wiki list: https://github.com/PistonDevelopers/piston/wiki/Games-Made-With-Piston

If you have a suitable screenshot, then we can replace "Playform" on the front page. This is a project that no longer uses Piston.

The repo for the website is:
https://github.com/PistonDevelopers/pistondevelopers.github.io

**Comment by christopherdumas** [comment]
We have a lot of pretty great screenshots, but our artist is in the process
of revamping the graphics so I’ll get back to you when that’s done.
Awesome, thanks! I’ll make my PR there.
