### ISSUE TITLE
Default www.piston.rs URLs to HTTPS

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/piston#1246]
Right now, www.piston.rs defaults to insecure HTTP. But https://www.piston.rs also works, but is just not default. 

The Documentation and Blog links at the top should also default to HTTPS instead of HTTP. Modern browsers are showing warnings to users and may turn some users away from the site.

**Comment by leonkunert** [comment]
ok fixed the link to the docs in this repo. I think that was the only one.

**Comment by johnthagen** [comment]
@leonkunert These two links still go to HTTP URLs as of this morning.

<img width="195" alt="screen shot 2018-10-18 at 7 52 30 am" src="https://user-images.githubusercontent.com/10340167/47152354-74c2d900-d2aa-11e8-8f44-872ecd1729e1.png">

**Comment by johnthagen** [comment]
This link also is going to HTTP:

<img width="360" alt="screen shot 2018-10-18 at 7 54 34 am" src="https://user-images.githubusercontent.com/10340167/47152434-b3589380-d2aa-11e8-9334-2a950525fc79.png">

**Comment by johnthagen** [comment]
Should be fixed in https://github.com/PistonDevelopers/pistondevelopers.github.io/pull/119
