### ISSUE TITLE
Reporting suspicious activity - revoking all permissions to prevent potential malicious attacks through Github or crates.io

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1257]
Attention @PistonDevelopers/pistoncollaborator @PistonDevelopers/admins @PistonDevelopers/owners 

17 hours ago, a Github account, who has never contributed to commits or issues, added public deploy key `05:99:67:68:24:55:9f:98:c8:25:44:ec:76:10:ee:aa` to all repositories under the PistonDevelopers organization. These keys were removed immediately upon discovery. The user's membership was removed from the organization.

As by default, all members have now their permissions revoked. The Piston project will shut down temporarily until our security policies have been reviewed.

I ran through a todo-list produced by Eco, removed all owners on crates.io except myself. Will check the repositories manually to see if there are remaining crates that might be targeted through crates.io.

There has been no detected attacks so far, but I'll keep looking.

**Comment by simnalamburt** [comment]
Nice catch! I am always thankful for your steady dedication to Piston.

**Comment by simnalamburt** [comment]
About password of GitHub account, parhaps this might be the perfect timing to force MFA to the members of PistonDevelopers. Just like this;

<img width="1002" alt="2018-12-26 11 29 49" src="https://user-images.githubusercontent.com/4435445/50429471-ffa2fe00-0901-11e9-9834-a81f326928e1.png">

**Comment by HeroicKatora** [comment]
Although 2FA is still a bit of a hazzle, and I'm unconvinced about the promised security improvements when using a high-entropy random password. My view on the topic may change when FIDO U2F (or equivalent) gets browser support not only from Chrome. However, while enforcing 2FA for accounts with administrative priviledges could be reasonable I would not want to (yet) have that burden on just any membership. Just not sure.

**Comment by simnalamburt** [comment]
Currently there's no good way to enforce MFA only to the administrator group. But admins can manually review each other admins' MFA status though.

By the way Firefox supports WebAuthn API. They do not support only U2F.

**Comment by larsbergstrom** [comment]
Yes, I'd highly encourage at least requiring MFA of all owners, and
possibly considering members as well, especially with the presence of
software MFA such as Google Authenticator. The benefit is not about adding
entropy (though that is great and should be encouraged!) but about
preventing replay attacks where a compromised session or machine provides
unlimited access to high-privilege actions to an attacker.

**Comment by hauleth** [comment]
Ekhm… #851

**Comment by fintelia** [comment]
After all of these changes I seem to have lost write access to all of the piston repositories. Was this intentional? And if so what is the new process for gaining write/merge access to repositories?

**Comment by bvssvni** [comment]
@fintelia Yes, this was intentional to prevent damage until the situation was analyzed.

The Admin group has now "Admin" access to all repositories. This group can add collaborators with write access by need, until the new policy of the PistonDevelopers team is resolved.

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/piston/pull/1263 to update to new policy of inviting people to the PistonCollaborator.

If there are no objections or feedback in 24 hours, I will merge this and set back "Write" permissions to all repositories for the PistonCollaborator team. I believe this is the right setting since we get some control over who's get invited as collaborators in other ways (only Admin team should do that).

I plan to create a separate team with owner permissions on crates.io. This will split the attack surface into two parts and make the project less attractive as a target.

**Comment by bvssvni** [comment]
The new team is now set up with permissions to publish. See https://github.com/PistonDevelopers/piston/issues/1265

Closing.
