### ISSUE TITLE
How to publish on crates.io

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1265]
The PistonDevelopers organization separates ownership on crates.io from teams with write access on Github, in order to reduce attack surface and make the project less attractive as a target.

There are 3 ways you can get a new version published on crates.io:

1. Ask @PistonDevelopers/publish to publish after updating the version and the crate is ready
2. Ask to be added as owner (this might be desirable for maintainers that do not want to help out with publishing other crates)
3. Ask to be added to @PistonDevelopers/publish

To be added to @PistonDevelopers/publish, you can ask below or send an email to any on the Owners team (e.g. @bvssvni).

These are the requirements to be added to @PistonDevelopers/publish:

1. Contributed long term to the Piston project or other projects in the Rust open source community
2. The judgement about experience is made informally by the people who invite
3. Willing to help out with getting crates published by need
4. Inactive members are removed after one year without warning, but might be re-invited by need

The purpose with these rules is to keep the team with publish permissions on crates.io small and effective, since this is largest source of code distribution.

**Comment by theotherphil** [comment]
I'd like to recover my ability to publish the imageproc crate. I don't mind whether this happens by adding me as an owner directly on crates.io or by adding me to the appropriate PistonDevelopers team.

**Comment by bvssvni** [comment]
@theotherphil Are you fine with helping out publishing from time to time?

**Comment by theotherphil** [comment]
I'm not able to devote much spare time to maintaining the piston ecosystem, but I'm willing to publish new versions of specific crates when requested if that's all that's required.

**Comment by bvssvni** [comment]
@theotherphil Thanks! I invited you to the publish team.

**Comment by theotherphil** [comment]
Great, thanks!

**Comment by bvssvni** [comment]
Closing.
