### ISSUE TITLE
An important reminder to people who might plan potential attacks against the Piston project as a joke

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1275]
Lately, the Piston project has experienced several potential security threats due to suspicious activity. It is suspected that some of these incidents are politically motivated.

Due to the risk of attracting more attackers, perhaps of desire to achieve status (perhaps as a "black hat") or because of a belief that "people on their side" (political motivation) see the Piston project as a target, I (@bvssvni, leader of the Piston project) have to remind potential attackers of the following:

- Criminal acts against people or property do not fall under the policies of the Piston project, but under the jurisdiction of legal authorities for that respective country which the person/people involved reside.
- There is nothing the Piston project can do to prevent or stop non-proportional retaliation from legal authorities. **None.** People working under the Piston project might report incidents to legal authorities if they feel threatened or violated, e.g. by attacks intended to intimidate or destroy property. If the attack is reported to legal authorities and the identity of the attacker is revealed, the attacker must be prepared to face legal consequences. In particular, *politically motivated attackers* have high risk of making irrational judgements about the expected consequences of their actions. For example by cognitive bias that "people think like me so I'm safe" or that they only expect that their target will be the one to expect potential retaliation from.
- Since the Piston project hosts development of some widely used libraries, any attack might be seen as a potential threat to the security infrastructure of outside actors. This includes potentially large and powerful institutions like governments in various countries, military forces or intelligence agencies. For example, the attacker might make a judgement about the security analysis of the Piston project, but forget that outside actors run their own analysis where any attack might be considered coming from a military enemy. This means that the identity of the attacker might have higher chance of getting revealed than for usual targets, leading to higher risk of legal consequences for the attacker and more severe consequences if there is suspected evidence of aiming at such institutions.
- **Therefore, it is strongly recommended, to remind, in particular for people with a history of mental illness or otherwise might have chronic or episodic impaired cognitive function: Do not attack the security structure of the Piston project for any reason.** For example, a person might view the act of attacking the Piston project as a harmless joke, but even if some people working here might find it amusing, it is not certain that everybody will find it funny. In particular, if the attacker commits a criminal act or create suspicious activity that might be viewed as a security threat to powerful institutions like governments in various countries.

Per security analysis of today, any attack will very likely have none or little consequence to the Piston project, except time delay. Therefore, it is expected that most attacks will be irrationally motivated in case they seek to harm this project. The most expected category of attackers are people who are mentally ill, politically motivated, or both, in which mental state there is a higher risk of making irrational choices.

It is very unlikely that large institutions or organizations will view the Piston project as a threat, but e.g. viruses and malware in widespread targets or aiming for such organizations might accidentally also be targeting property of people working under the Piston project. For this reason, security agencies might be monitoring public logs and reports to detect potential threats to their own infrastructure.

The attacker might face non-proportional consequences that they did not consider when planning the attack. This depends on whether criminal acts are made against individuals, or outside actors that consider an attack as something to investigate for security reasons.

**Comment by bvssvni** [comment]
Closing since there are no signs of this kind attack. Apparently it's just bots.

**Comment by KenSuenobu** [comment]
You may want to reconsider posting things like this without doing prior research: you're going to scare off a LOT of developers.
