### ISSUE TITLE
Window icon?

### ISSUE THREAD

**Issue by AregevDev** [PistonDevelopers/piston#1279]
How can I set a window icon to the window backends?
There is nothing documented online regarding this.
Do I need to access the window backend manually?

**Comment by bvssvni** [comment]
Yes, you need to set it manually.

**Comment by AregevDev** [comment]
Works well, but still dirty and verbose. Any chance of providing a nice way to set it in the next versions of `*-window`? Should I submit a PR?

**Comment by bvssvni** [comment]
PRs are welcome!

**Comment by AregevDev** [comment]
Hi, these are the things I will to change:

Add an icon field to `Window` and `WindowSettings` structs
Add the corresponding builder functions
Re-export the `Icon` struct from `winit` / `glutin`

**Comment by AregevDev** [comment]
Forgot `Window` is actually a trait...
Also, I have a problem with the Icon struct: since it does not belong to piston itself, and piston does not relay either on `winit` or `glutin` by default, how should I handle this situation?

**Comment by AregevDev** [comment]
We may want to move this conversation somewhere else

**Comment by bvssvni** [comment]
`Icon` could be made an associated type on the `AdvancedWindow` trait.

**Comment by bvssvni** [comment]
Perhaps we could use a type that gets converted to back-end specific formats for icons?

**Comment by LionKing27** [comment]
How do I access the window backend?

**Comment by bvssvni** [comment]
@LionKing27 the window backend is the type that implements `Window` and `AdvancedWindow`. For example, in the `pistoncore-sdl2_window` library, the window backend is `Sdl2Window`.

**Comment by adumbidiot** [comment]
Maybe the Icon type could just be an rgba buffer?

**Comment by bvssvni** [comment]
Closing since this is possible to do with the window backend.
