### ISSUE TITLE
Fix SDL2 dependancy in FreeType example

### ISSUE THREAD

**Issue by Dunnings** [PistonDevelopers/piston#1280]
The freetype example is fixed to using SDL2-Window instead of the generic PistonWindow and therefore cannot be combined with the other examples like src/sprite.rs.

**Comment by Dunnings** [comment]
I fixed this [here](https://github.com/Dunnings/piston-examples/commit/9642f5b89b299abcabb9f0ce0eab62dc89e20d57). I'm not sure how I commit a PR to the [https://github.com/PistonDevelopers/piston-examples](https://github.com/PistonDevelopers/piston-examples) repositiory..

**Comment by bvssvni** [comment]
Closing.
