### ISSUE TITLE
Broken Example Code on https://www.piston.rs/

### ISSUE THREAD

**Issue by hasahmed** [PistonDevelopers/piston#1283]
Trying to get the engine up and running the example code on https://www.piston.rs/ seems to be broken. The error says that the lambda on line 10 expects 3 arguments, so I added another one. This is my first foray into Rust so apologies if it sounds like I don't know what I'm talking about (I don't).

And yeah adding a 3rd argument fixed the issue.

Here is my Cargo.toml file

[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"

[dependencies]
piston = "0.43.0"
piston_window = "0.93.0"
piston2d-graphics = "0.32.0"
pistoncore-glutin_window = "0.55.0"
piston2d-opengl_graphics = "0.62.0"
find_folder = "0.3.0"

**Comment by bvssvni** [comment]
Thanks! I opened https://github.com/PistonDevelopers/pistondevelopers.github.io/pull/121

**Comment by bvssvni** [comment]
Fixed.

Closing.
