### ISSUE TITLE
Additive blending with alpha channel

### ISSUE THREAD

**Issue by 3c1u** [PistonDevelopers/piston#1327]
Hi, I'm using Piston for my game development and I thought that adding a blending mode such as "Screen" like in Photoshop will be convenient.

I've tried `Blend::Add` and it was disappointing because it doesn't handle alpha channel, whereas `lighter` mode in `CanvasRenderingContext2D::globalCompositeOperation` (JavaScript/HTML5 Canvas) does. I modified the `graphics` crate ([3c1u/gfx_graphics](https://github.com/3c1u/gfx_graphics) and [3c1u/graphics](https://github.com/3c1u/graphics)) to replicate this as `Blend::Screen`.

I drew `rgba(0, 0, 255, 0.5)` (left) and `rgba(0, 0, 255, 1.0)` (right) over `rgba(255, 0, 0, 1.0)` and the following images are the results.

top: `lighter` (HTML5 Canvas), bottom: `Blend::Screen` (modified Piston)

![スクリーンショット 2019-07-20 21 45 18](https://user-images.githubusercontent.com/298748/61578846-e8df2580-ab37-11e9-805e-2a0e166f9e1b.png)

top: `lighter` (HTML5 Canvas), bottom: `Blend::Add` (unmodified Piston)

![スクリーンショット 2019-07-20 21 45 21](https://user-images.githubusercontent.com/298748/61578859-1b891e00-ab38-11e9-9663-93f05739cec1.png)

Is it possible to add this feature to Piston, as well as other graphic backends?

**Comment by bvssvni** [comment]
Yes! Can you make a PR?

**Comment by 3c1u** [comment]
Renamed to `Blend::Lighter` (because it was actually different from "Screen" from Photoshop) and made a PR (https://github.com/PistonDevelopers/graphics/pull/1131). Thank you.
