### ISSUE TITLE
Hi. Is this thing on?

### ISSUE THREAD

**Issue by felix91gr** [PistonDevelopers/piston#1336]
A friend of mine is looking for a good game engine he can use to work on his project. Seeing that the last update was around 6 months ago... should he try Piston, or is the project no longer being worked on?

Thanks in advance! :)

**Comment by jmwielandt** [comment]
+1
cps~

**Comment by bvssvni** [comment]
This is still being worked on, but not as frequent as most things are stable.

**Comment by bvssvni** [comment]
Closing.
