### ISSUE TITLE
piston::window doesn’t support the `transparent` attribute

### ISSUE THREAD

**Issue by ticky** [PistonDevelopers/piston#1338]
I’m attempting to build a floating window whose background is transparent. It looks like the underlying windowing implementation [would support this across Windows, Mac and Linux](https://github.com/rust-windowing/winit/blob/098fd5d602ee3b20372048db35aa3de432884aaa/FEATURES.md#windowing-1), however, piston doesn’t expose enough of the window attributes [from `WindowSettings`](https://github.com/PistonDevelopers/piston/blob/master/src/window/src/lib.rs#L403-L423) to enable this feature.

The underlying feature seems relatively straightforward to add, presumably by adding a field [matching this one](https://github.com/rust-windowing/winit/blob/c2aed1979d147a0fe64e2054ad416339a2bbffe1/src/window.rs#L281-L286) to [`piston::window::WindowSettings`](https://github.com/PistonDevelopers/piston/blob/master/src/window/src/lib.rs#L403-L423) and plumbing it through to `glutin_window`.

Is this functionality which has been deliberately excluded, or would a set of PRs adding this to the requisite components be something you’re interested in?

**Comment by bvssvni** [comment]
I agree, this window setting should be added. PRs are welcome!

**Comment by gcstr** [comment]
Although I can see that this setting is now exposed. It doesn't seem to work for me https://github.com/PistonDevelopers/piston_window/issues/288
Is there any other setting required?

**Comment by StevenLu2004** [comment]
The PR ([PistonDevelopers/piston/pull/1345](https://github.com/PistonDevelopers/piston/pull/1345/files)) doesn't implement the settings for any of the window backends tho. It literally only adds a field to `WindowSettings` which doesn't even get read in the `GlutinWindow::new()` source.
