### ISSUE TITLE
New line bytes appear as boxes.

### ISSUE THREAD

**Issue by hellbound22** [PistonDevelopers/piston#1339]
Code snip:
```rust
let mut char_cache = window.load_font("/usr/share/fonts/liberation/LiberationMono-Reg    ular.ttf").unwrap();
/***** *****/
text::Text::new_color([1.0, 1.0, 1.0, 1.0], font_size).draw(
    &format!("Quantidade \n/U+000Ade estrelas na câmera: {}",
        cam_map.len(),
    ),
    &mut char_cache,
    &context.draw_state,
    transform, graphics
).unwrap();
```
Result:
![image](https://user-images.githubusercontent.com/22417233/78246945-5cf00c80-74c0-11ea-9383-6b0a542286c9.png)

Am I doing something wrong here?

**Comment by bvssvni** [comment]
I believe that newline characters are placeholder symbols. The font engine can't know where the beginning of a line is, so instead of doing this directly, it is the job of the application logic to handle this.

**Comment by bvssvni** [comment]
Closing.
