### ISSUE TITLE
Fullscreen Screencapture does not work on WIndows10

### ISSUE THREAD

**Issue by kgrzywocz** [PistonDevelopers/piston#1349]
Original issue is about testing the [league_of_steel](https://github.com/kgrzywocz/league_of_steel) (it captures screen using Dx9), but there is an easier way to reproduce it using [miniview](https://github.com/foresterre/miniview) - which is less complex and Windows 10 build-in functionality:

1) ```cargo install miniview```
2) ```miniview --fullscreen --from-path <some png image>```
3) Press 'Print Screen' key
4) Open ```mspaint.exe``` and press Ctrl-V

Expected: screen you can see on your display
Actual result: white image/black screen with white image on it

This issue is observed only on Windows 10 with Intel Graphics. On Windows 7 it works fine.
Also it seams to be only problem with ```.fullscreen(true)``` option set - windowed mode works fine

Any ideas what might be wrong?

**Comment by kgrzywocz** [comment]
I think this is may be more windows issue - it works on windows 18xx, but not on 1909.

**Comment by bvssvni** [comment]
Closing. Reopen if this is still an issue.
