### ISSUE TITLE
Piston + Rust remote development environment

### ISSUE THREAD

**Issue by ragnta** [PistonDevelopers/piston#1350]
I am using vagrant vm for learning/developing rust. ( https://app.vagrantup.com/bento/boxes/ubuntu-19.10 )
Is there any solution to run/compile the piston application to Windows on Linux?

I tired to use x11_forwarding with VcXsrv and XMing and I got the following error: ``` CreationErrors([Window(OsError("No monitors were detected.")), OsError("`glXQueryExtensionsString` found no glX extensions")])' ``` I think it's a driver problem of the vm machine.
I also tried to use the sdl2_window lib of piston https://crates.io/crates/pistoncore-sdl2_window,
I got the following error: ``` .cargo/registry/src/github.com-1ecc6299db9ec823/sdl2-0.34.1/src/sdl2/video.rs:1510: undefined reference to `SDL_SetWindowOpacity' ``` 

I tried also the sdl2 with c++ on the same environment, and the x11_forwarding is working fine.

**Comment by ragnta** [comment]
The `No monitors were detected.` error is from the winit 3rd party. After the v0.20.0-alpha4 the winit create a dummy window if there is no monitor detected. As I saw the piston is using 1.19.

**Comment by bvssvni** [comment]
I got a similar error with SDL2 on OSX, which was fixed by updating SDL2.

**Comment by bvssvni** [comment]
Closing. Reopen if this is still an issue.
