### ISSUE TITLE
Which platforms supported for building?

### ISSUE THREAD

**Issue by ProgrammingLife** [PistonDevelopers/piston#1351]
I've not found any information about platforms for which Piston can build games. Can it build for mobile platforms such as iOS and GooglePlay?

**Comment by bvssvni** [comment]
In theory, Piston can build for any platform supported by Rust. However, this requires custom setup for platforms beside major operating systems. Currently there is no list of platforms which are easy to set up.

**Comment by ProgrammingLife** [comment]
@bvssvni I get it. It's just not the main goal for the engine to build it to platrorms. Ok, I should find some information on how to build rust code into thouse platform. Thanks!

**Comment by ProgrammingLife** [comment]
@bvssvni by the way. Does this engine use OpenGL or GLES? I think there maybe some problems with building to mobile platforms as it supports gles only.

**Comment by bvssvni** [comment]
@ProgrammingLife When targeting Emscripten or WebGL, the OpenGL backend detects this automatically: https://github.com/PistonDevelopers/opengl_graphics/blob/master/src/back_end.rs#L24
