### ISSUE TITLE
Getting Started issue crashes 

### ISSUE THREAD

**Issue by faxe1008** [PistonDevelopers/piston#1367]
I am trying to run the getting-started example with the spinning square and I can see a window flashing and then the app crashes and prints:
```
libEGL warning: DRI2: failed to authenticate
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t find any available vsync extension")])', src/main.rs:58:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

System Information:
- piston = "0.52.0"
- piston2d-graphics = "0.39.0"
- pistoncore-glutin_window = "0.68.0"
- piston2d-opengl_graphics = "0.77.0"
- OS: Arch Linux 64Bit run within virtual box, 5.9.1-arch1-1 with X11 and xorg-server
- rustc 1.48.0
- cargo 1.48.0

**Comment by shinmili** [comment]
Could [this information](http://www.is.chs.nihon-u.ac.jp/students/file/GL3bc_notavailable.pdf) help you? On the last page it says if you have "libEGL warning: DRI2: failed to authenticate" message, try turning on "Enable 3D Acceleration".

**Comment by Irgendwer01** [comment]
@faxe1008 u need to enable 3D Acceleration in Virtualbox and Virtualbox guest additions for it to work properly. 
![grafik](https://user-images.githubusercontent.com/67506320/155131695-fdf2aaa8-176c-48f8-afb1-599f5c37abe1.png)

**Comment by bvssvni** [comment]
Closing. Reopen if this is still an issue.
