### ISSUE TITLE
Rename "master" to "main" on all repositories

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#1368]
See https://github.com/github/renaming

Github and Git changes the default branch name from "master" to "main", recognizing that "master" is offensive to some people.

Cultural issues aside, in order to keep naming of branches consistent across all projects and avoid papercuts, I suggest we rename "master" to "main" on all repositories.

**Comment by kotx** [comment]
Currently it seems "master" is more commonly used though. Renaming now might cause more trouble than it's worth.

**Comment by bvssvni** [comment]
Closing since "master" is still used, except new projects.
