### ISSUE TITLE
Are there chat forums such as Discord out there?

### ISSUE THREAD

**Issue by Joe23232** [PistonDevelopers/piston#1380]
Are there chat forums such as Discord out there for Piston?

**Comment by bvssvni** [comment]
Yes, https://discord.com/invite/TkDnS9x

**Comment by Joe23232** [comment]
Ok thanks mate

**Comment by shinmili** [comment]
Maybe best to put a link in https://www.piston.rs or README.md?

**Comment by bvssvni** [comment]
Added to README.md.

Closing.
