### ISSUE TITLE
Is there a way to capture a screen state and saving it to png using just Piston?

### ISSUE THREAD

**Issue by ProgrammingLife** [PistonDevelopers/piston#1381]
I need to create some sort of video files of gameplay without any external tools using just Piston. So I wanna start with saving just one frame to png file. How do I do it?

**Comment by bvssvni** [comment]
You can use https://crates.io/crates/graphics_buffer

**Comment by ProgrammingLife** [comment]
@bvssvni  Can it be used without creating opengl/vulkan context? For using it for console rendering without having GPU card

**Comment by bvssvni** [comment]
Yes, you can use `NoWindow`.

**Comment by ProgrammingLife** [comment]
@bvssvni Piston can work and render in texture without GPU card using just CPU? 
Sorry for bothering you, but it sounds incredible too me, that's so cool if it can work on servers without gpu.

**Comment by bvssvni** [comment]
@ProgrammingLife  yes, the graphics_buffer library only uses CPU.
