### ISSUE TITLE
WindowSettings online docs are out of date

### ISSUE THREAD

**Issue by benliepert** [PistonDevelopers/piston#1385]
The online documentation for WindowSettings, linked in the readme (points to [here](https://docs.piston.rs/piston/window/struct.WindowSettings.html)), is out of date.
I pulled piston v0.53.1 and the `WindowSettings::opengl()` and `WindowSettings::set_opengl()` methods aren't available. I noticed this because the Piston-Tutorials "getting-started" example ([here, line 55](https://github.com/PistonDevelopers/Piston-Tutorials/blob/master/getting-started/src/main.rs)) uses the `WindowSettings::graphics_api()` call, which isn't mentioned on docs.piston.rs.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston/commit/24c912a65ff57bdc107b1428e959e2444f56d937
