### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by rayanmargham** [PistonDevelopers/piston#1391]
Seems as if the maintainers of this project aren't very active as it hasn't been updated in 6 months

Last issues were on 2022

Have people given up on piston in favour of bevy? That'd be really sad if that's true I loved using piston

**Comment by bvssvni** [comment]
No, not dead, but there are no community projects, which is why there is little activity. The goal of stability is still on. I am currently busy doing mathematical research.
