### ISSUE TITLE
Add a webgl backend for rust-graphics

### ISSUE THREAD

**Issue by TyOverby** [PistonDevelopers/piston#484]
For when rust has emscripten support, being able to render to a webgl canvas would be amazing.

**Comment by nepp2** [comment]
With Rust now able to compile via emscripten and SDL2 apparently officially supported, does anyone know how much work would be required to make this happen? Also, do you guys know how much trouble it would be to get things like sound and input working? Thanks.

**Comment by bvssvni** [comment]
@nepp2 There has already been some work on this: https://github.com/PistonDevelopers/piston/issues/1131#issuecomment-269895770
