### ISSUE TITLE
List of features

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#668]
Notice: Moved to https://github.com/PistonDevelopers/piston/wiki/Features.

This list is intended to be a rough reference of the features we provide in the Piston libraries:
- Game loop, implemented as iterator, which makes it possible to use one function per scene/mini game/dialogue
- Back-end agnostic, extensible, generic event programming (can be implemented on top of other libraries)
- AI behavior trees that transforms a declarative parallel processing event logic into a state machine (sounds scary, but simple to use)
- Back-end agnostic, fast 2D graphics triangulation for simple shapes
- Integration with OpenGL/Gfx/SDL2/GLFW/Glutin/Glium
- Immediate mode UI (Conrod), getting new features every week
- Image formats and processing PNG/JPEG/GIF and other formats
- Sprite scenes and animations
- Digital sound processing (developed under RustAudio organization)
- Font rendering with FreeType
- Vector math library with both row and column major matrices
- Quaternion math library
- Dual quaternion math library
- Shader version library for OpenGL
- Deform images in realtime
- Visual Studio plugin for Rust
- Asynchronous loading of assets from network, files, built-in binary data
- 3D camera and view/model/perspective setup
- First person camera controller
- Wavefront OBJ loader for 3D geometry
- Collada 3D format
- Skeleton animation blending
- Mouse/keyboard data structure (to be used in other libraries)
- FPS counter
- Texture packer

**Comment by ForsakenHarmony** [comment]
why is this not on the wiki?

**Comment by bvssvni** [comment]
Good idea! Perhaps we should make a wiki page?

**Comment by lucklove** [comment]
Wiki is better

**Comment by bvssvni** [comment]
Created https://github.com/PistonDevelopers/piston/wiki/Features, removed one outdated feature and added new ones. Updated top comment with to wiki.

**Comment by ForsakenHarmony** [comment]
Now just update the README.md ;)
