### ISSUE TITLE
Create a guide for creating an small game

### ISSUE THREAD

**Issue by svenstaro** [PistonDevelopers/piston#669]
Currently, coming from C++, I lack any kind of structure. Lacking classes, structs + impls take their place. How to properly use traits in this case? How to do Data Oriented Programming?

Especially since many hobby game developers are now coming from C++, it would be great to have some kind of general guide on how to make a game with Rust + Piston. Mostly, this is about module structure and game loop design.

**Comment by bvssvni** [comment]
Reopen an issue on https://github.com/pistondevelopers/piston-tutorials if you find it lacking material.

Closing.
