### ISSUE TITLE
Documentation hasn't be updated for a long time

### ISSUE THREAD

**Issue by huonw** [PistonDevelopers/piston#698]
https://github.com/hansjorg/rust-ci/issues/22 unfortunately means that the online docs are very out of date, e.g. the changes in https://github.com/PistonDevelopers/event/commit/e4d7b295f9bdf481d9b4ba9066cf0221cc58e897 are not reflected [in the docs](http://www.rust-ci.org/PistonDevelopers/piston/doc/piston/event/enum.Status.html) (one would expect the `Eq` and `Show` traits to appear in the list of derived implementations).

Strictly speaking this is not a piston bug, but I thought you may wish to know.

**Comment by bvssvni** [comment]
This is still a problem. piston-image added commands to .travis.yml to fix this https://github.com/PistonDevelopers/image/blob/master/.travis.yml

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/piston/issues/845

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston/pull/849
