### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#70]
The guidelines are moved [here](https://github.com/PistonDevelopers/piston/blob/master/CONTRIBUTING.md)

**Comment by davekong** [comment]
I want to contribute to Piston.

**Comment by bvssvni** [comment]
@davekong Welcome to the team! I sent you an invitation.

**Comment by alexchandel** [comment]
I've submitted a few PRs in the past, I'd like to contribute myself!

**Comment by bvssvni** [comment]
@alexchandel I thought you were on the team already. Sent you an invitation!

**Comment by tanadeau** [comment]
I want to contribute to Piston.

**Comment by bvssvni** [comment]
@tanadeau Welcome to the team! I sent you an invitation.

**Comment by aij** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@aij Welcome to the team! I sent you an invitation.

**Comment by andrensegura** [comment]
Howdy! I've just recently started learning Rust but I've been following it for quite some time. I plan on sticking with it. It's a really promising language and I'd love to see where it goes. It would be really cool to be a part of it's early development. Also, I've never done any open source work. This looks like lots of hard work and dedication. Any way I can get in on this? :)

**Comment by bvssvni** [comment]
@andrensegura Welcome to the team! I sent you an invitation.

I'm on IRC (#rust-gamedev) if you want some help to get started.

**Comment by pataroose** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@pataroose Welcome to the team! I sent you an invitation.

**Comment by michaelrutherford** [comment]
I've been following Piston for a while, and I would like to contribute to the project.

**Comment by michaelrutherford** [comment]
I've been following Piston for a while, and I would like to contribute to the project. @bvssvni

**Comment by azilber** [comment]
Hi Sven!  I'd like to contribute as well!  @bvssvni

**Comment by bvssvni** [comment]
@michaelrutherford Welcome to the team! I sent you an invitation.

**Comment by bvssvni** [comment]
@azilber Welcome to the team! I sent you an invitation.

**Comment by jeremija** [comment]
Hi guys, I'm just about to finish the Rust book. I like it so far, but some concepts seem hard to grasp without seeing them in action. I'd really like to learn more by contributing to a larger project such as this one. My background is in Java, JavaScript, Python and I have limited experience with C and C++. Would it be possible for me to join and try to contribute?

**Comment by bvssvni** [comment]
@jeremija Welcome to the team! I sent you an invitation.

**Comment by dunnker** [comment]
I would like to contribute a sample "hello world" project for rendering text. I had to figure it out for my tetris game, but now that I know how to do it, I'd like to help anyone else looking for sample projects.
If there are other tutorial projects I can help with I would be willing to contribute!

**Comment by bvssvni** [comment]
@dunnker There is an example like that here: https://github.com/PistonDevelopers/piston-examples/blob/master/src/hello_world.rs

**Comment by bvssvni** [comment]
@dunnker Welcome to the team! I sent you an invitation.

**Comment by dannyflax** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@dannyflax Welcome to the team! I sent you an invitation.

**Comment by RDeckers** [comment]
I'm looking to contribute to Piston.

**Comment by bvssvni** [comment]
@RDeckers Welcome to the team! I sent you an invitation.

**Comment by KevinFrans3** [comment]
Hey I'm looking to contribute to piston

**Comment by bvssvni** [comment]
@KevinFrans3 Welcome to the team! I sent you an invitation.

**Comment by renlok** [comment]
I would like to contribute

**Comment by bvssvni** [comment]
@renlok Welcome to the team! I sent you an invitation.

**Comment by theotherphil** [comment]
I would like to contribute to piston

**Comment by bvssvni** [comment]
@theotherphil Welcome to the team! I sent you an invitation.

**Comment by DanTheColoradan** [comment]
I would like to contribute to piston

**Comment by bvssvni** [comment]
@DanTheColoradan Welcome to the team! I sent you an invitation.

**Comment by mpatraw** [comment]
I would like to contribute. Thanks!

**Comment by bvssvni** [comment]
@mpatraw Welcome to the team! I sent you an invitation.

**Comment by ryo33** [comment]
I would like to contribute.

**Comment by bvssvni** [comment]
@ryo33 Welcome to the team! I sent you an invitation.

**Comment by yeliknewo** [comment]
I would like to contribute.

**Comment by ConnorGBrewster** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@yeliknewo Welcome to the team! I sent you an invitation.

**Comment by bvssvni** [comment]
@ConnorGBrewster Welcome to the team! I sent you an invitation.

**Comment by sezna** [comment]
I want to contribute to Piston, and I want to make my message unique.

**Comment by bvssvni** [comment]
@sezna Welcome to the dark side! I sent you an invitation.

:smiling_imp:  Mwuhahaha!

**Comment by getynge** [comment]
I want to contribute to piston

**Comment by bvssvni** [comment]
@getynge Welcome to the team! I sent you an invitation.

**Comment by chylli** [comment]
I want to contribute to hematite

**Comment by bvssvni** [comment]
@chylli Welcome to the team! I sent you an invitation.

**Comment by michaelmera** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@michaelmera Welcome to the team! I sent you an invitation.

**Comment by stonecompass** [comment]
I want to contribute to Piston :-)

**Comment by bvssvni** [comment]
@stonecompass Welcome to the team! I sent you an invitation.

**Comment by simnalamburt** [comment]
I want to contribute to Piston project. Especially to the 2D graphics related projects. ([texture_packer]( https://github.com/PistonDevelopers/texture_packer), [graphics](https://github.com/PistonDevelopers/graphics), etc)

**Comment by bvssvni** [comment]
@simnalamburt Welcome to the team! I sent you an invitation.

**Comment by sunjay** [comment]
I want to contribute to Piston.

**Comment by bvssvni** [comment]
@sunjay Welcome to the team! I sent you an invitation.

**Comment by Christopher22** [comment]
I want to contribute to Piston and make the world and the game development a bit more "rusty", too ;)

**Comment by bvssvni** [comment]
@Christopher22 Welcome to the team! I sent you an invitation.

**Comment by clicketyclack** [comment]
I want to contribute to Piston.

**Comment by bvssvni** [comment]
@clicketyclack Welcome to the team! I sent you an invitation.

**Comment by tomgosling** [comment]
I want to contribute!

**Comment by bvssvni** [comment]
@tomgosling Welcome to the team! I sent you an invitation.

**Comment by kblanks** [comment]
Hey! I'd like to contribute to Piston (probably hematite or the 3D libraries). I'm kinda new to Rust but I've got lots of experience in other languages and I've been picking it up pretty fast.

**Comment by bvssvni** [comment]
@kblanks Welcome to the team! I sent you an invitation.

**Comment by oldmanmike** [comment]
GREETINGS!!! I would like to contribute to the Piston ecosystem and Rust game development in general. I've got some work in writing a Minecraft server in Haskell that I would like send Hematite's way, provided The Dude Abides.

**Comment by bvssvni** [comment]
@oldmanmike Welcome to the team! I sent you an invitation.

**Comment by lucklove** [comment]
I'd like to do everything in my power, for piston.  @bvssvni

**Comment by bvssvni** [comment]
@lucklove Welcome to the team! I sent you an invitation.

**Comment by rosshays** [comment]
I want to contribute.

**Comment by tomgosling** [comment]
I want to contribute to Piston! 💯

**Comment by bvssvni** [comment]
@tomgosling Welcome to the team! I sent you an invitation.

**Comment by MarkMcCaskey** [comment]
Hello, hello.
I'd like to contribute.  Looking at Conrod, but I'm interested in many things.

**Comment by bvssvni** [comment]
@MarkMcCaskey Welcome to the team! I sent you an invitation.

**Comment by BedfordWest** [comment]
I would love to contribute. I'm working on making some games utilizing Piston and other Rust tools, and I'm finding myself wanting to contribute to various parts of the Piston ecosystem. I hope to be useful!

**Comment by bvssvni** [comment]
@BedfordWest Welcome to the team! I sent you an invitation.

**Comment by vitvakatu** [comment]
Hello! I want to contribute to Conrod

**Comment by bvssvni** [comment]
@vitvakatu Welcome to the team! I sent you an invitation.

**Comment by emil-petersen** [comment]
I want to contribute.

**Comment by bvssvni** [comment]
@emil-petersen Welcome to the team! I sent you an invitation.

**Comment by emil-petersen** [comment]
@bvssvni Thank you.

**Comment by phaazon** [comment]
I want to contribute to Piston.

I have pushed several commits to [wavefront_obj](https://github.com/PistonDevelopers/wavefront_obj) already and might go on in the next future to maintain it.

**Comment by bvssvni** [comment]
@phaazon Welcome to the team! I sent you an invitation.

**Comment by brettfo** [comment]
I want to contribute to Piston.

I've already submitted a PR adding simple BMP encoding to the `image` crate.  PistonDevelopers/image#646.

**Comment by bvssvni** [comment]
@brettfo Welcome to the team! I sent you an invitation.

**Comment by Xaeroxe** [comment]
I want to contribute to Piston.

**Comment by bvssvni** [comment]
@Xaeroxe Welcome to the team! I sent you an invitation.

**Comment by lukors** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@lukors Welcome to the team! I sent you an invitation.

**Comment by vrecluse** [comment]
I want to contribute to Piston.
@bvssvni

**Comment by bvssvni** [comment]
@vrecluse Welcome to the team! I sent you an invitation.

**Comment by tomgosling** [comment]
I want to contribute to Piston :) @bvssvni

**Comment by bvssvni** [comment]
@tomgosling Welcome to the team! I sent you an invitation.

**Comment by vignesh-sankaran** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@vignesh-sankaran Welcome to the team! I sent you an invitation.

**Comment by difarem** [comment]
i want to contribute to Piston

**Comment by bvssvni** [comment]
@difarem Welcome to the team! I sent you an invitation.

**Comment by notryanb** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@notryanb Welcome to the team! I sent you an invitation.

**Comment by anthonynguyen** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@anthonynguyen Welcome to the team! I sent you an invitation.

**Comment by HeroicKatora** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@HeroicKatora Welcome to the team! I sent you an invitation.

**Comment by 335g** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@335g Welcome to the team! I sent you an invitation.

**Comment by collin5** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@collin5 Welcome to the team! I sent you an invitation.

**Comment by leftiness** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@leftiness Welcome to the team! I sent you an invitation.

**Comment by PinkFloyded** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@PinkFloyded Welcome to the team! I sent you an invitation.

**Comment by dineshadepu** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@dineshadepu Welcome to the team! I sent you an invitation.

**Comment by bvssvni** [comment]
@robot0 Welcome to the team! I sent you an invitation.

**Comment by quietlychris** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@quietlychris Welcome to the team! I sent you an invitation.

**Comment by fintelia** [comment]
I want to contribute to Piston

**Comment by fintelia** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@fintelia Welcome to the team! I sent you an invitation.

**Comment by self-unaware** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@self-unaware Welcome to the team! I sent you an invitation.

**Comment by lazypassion** [comment]
I want to contribute to piston

**Comment by bvssvni** [comment]
@lazypassion Welcome to the team! I sent you an invitation.

**Comment by KenSuenobu** [comment]
Would like to contribute.  I have several years of development with Atari GEM (helped with several GEM projects) and some experience with Qt/KDE.  Would like to help simplify the library, and make things more efficient!

**Comment by Kagami** [comment]
I think I wasn't officially invited, so commenting here just in case. I'm contributing to 3 repos:
https://github.com/PistonDevelopers/gfx_text
https://github.com/PistonDevelopers/resize
https://github.com/PistonDevelopers/y4m
and would like to keep access to them. Thanks.

**Comment by retep998** [comment]
Since I haven't had any comments on this issue yet but have been in the organization for a while and have contributed, I'd like to retain my status.

**Comment by bvssvni** [comment]
@Kagami @retep998 no problem!

**Comment by shanehandley** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@shanehandley Welcome to the team! I sent you an invitation.

**Comment by gratispress** [comment]
Hello, I am writing a book on Rust. One of the requested things in my surveying results is more GUI coverage in the literature. I am not certain of my financial ability to do so at the current time; however, I would like to pay $500 or so toward having a professional, clean set of widgets made for this GUI toolkit, aiming to blend in most with Linux styles but to be not out of place too much anywhere, with the aim of it being very modern looking graphically. 

Again, there is only about a 20% chance I will be able to actually do this; however, if I can donate for this to be done, and if I manage the interaction with the professional graphics artists, and provide your input to them, but also do any required Rust oriented programming stuff for them, can I have some degree of reassurance that you would like a professional set of graphical widgets with a modern look to them, at that I can receive credit for donating this, as well as draw attention to having done so in my book?

**Comment by gratispress** [comment]
I can also perhaps provide you with Rust code and associated graphics rendering for an element that render survey results in various forms such as bar graphs, pie graphs, and various such things, as an additional element for your toolkit, and a set of skins with it. For I plan to be demonstrating various things in such forms anyway, so having the ability to "kill two birds with one stone" by improving GUI support in Rust and also making myself a beautiful graph widget, is awesome if we can do it. Anyway, I eagerly await feedback regarding these options.

**Comment by bvssvni** [comment]
@gratispress Can you open up a new issue to discuss this? This thread is for people who want to contribute to Piston and need write access.

**Comment by bodagovsky** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@bodagovsky Have you read https://github.com/PistonDevelopers/piston/blob/master/CONTRIBUTING.md#becoming-a-part-of-the-pistoncollaborator-team ? You don't need write access to contribute.

**Comment by mario-s** [comment]
I want to contribute to Piston

**Comment by bvssvni** [comment]
@mario-s Have you read https://github.com/PistonDevelopers/piston/blob/master/CONTRIBUTING.md#becoming-a-part-of-the-pistoncollaborator-team ? You don't need write access to contribute.
