### ISSUE TITLE
Should piston projects closely follow the rust style guide?

### ISSUE THREAD

**Issue by jemcroft** [PistonDevelopers/piston#700]
The rust team strongly encourages following style conventions as set out in the lints in the compiler and those in [rust-guidelines](https://github.com/rust-lang/rust-guidelines). Do we want to make a best effort attempt to abide by these style guidelines? This would make it easier to contribute to projects under the piston banner without introducing style inconsistences among projects.

I ask because the code in [wavefront-obj](https://github.com/PistonDevelopers/wavefront-obj/blob/master/src/obj.rs) uses 2 space for indents while the rust convention is to use 4 spaces. Personally I perfer 2 space indents, but having uniform style is better than having your favourite style.

Thoughts?

**Comment by bvssvni** [comment]
I created https://github.com/PistonDevelopers/piston/issues/844

Closing.
