### ISSUE TITLE
Failing builds, am I missing some clever trick?

### ISSUE THREAD

**Issue by eriksvedang** [PistonDevelopers/piston#772]
I've been using Piston on and off for the last few months. It's very fun but sometimes (like now) the build is not working. I realize it must be very hard to keep up with the fast pace of the Rust language and you also seem to experiment a lot with the api:s for Piston, which is cool. 

Perhaps there are some tricks I can use to build with an older but working version of Piston and Rust? Right now I'm using the latest nightly build and just adding dependencies to the cargo projects, following the Piston examples.

To be clear, I'm totally up for upgrading my code as API:s change and so on. As a rust beginner I'm a little unsure of how to keep that managable though, so if anyone has any tips for some kind of workflow I'd be very thankful!

Erik

**Comment by Phlosioneer** [comment]
This could probably be closed now, it's rather stale now.
