### ISSUE TITLE
Rust 1.0 Plans

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/piston#807]
Wow, according to [this](http://blog.rust-lang.org/2014/12/12/1.0-Timeline.html) the 1.0 alpha is only about 5 days away! Feels like it's coming out of nowhere! Though at the same time very welcome :)

I couldn't see any other issues raising this specifically so I thought I'd start a discussion where we can clarify the plans for the Piston repos as 1.0 arrives.

Once 1.0 lands I guess the primary aims are to be:
- 1.0 compatible. (no more breaking changes every few days! woohoo!)
- Available on crates.io

I guess it will be hard to tell until the alpha comes out in a few days, but it could be good to work out what sort of stuff we need to do / change to be 1.0 compatible (i.e. work around unstable feature gates, etc).

**Comment by mitchmindtree** [comment]
Also, I'm guessing we will remain on the nightlies throughout the alpha and beta until 1.0 lands?

**Comment by bvssvni** [comment]
Aren't there planned breaking changes between alpha and beta?

**Comment by bvssvni** [comment]
I think we should be on crates.io when Rust 1.0 is released. gl-rs will be 1.0 compatible, rust-sdl2 is already on crates.io.

**Comment by AngryLawyer** [comment]
I'll be turning sdl2 to 0.1.0 when Rust 1.0 is properly released, and I'll start being a lot more careful about breaking changes.

**Comment by bvssvni** [comment]
Rust 1.0 is out!

**Comment by mitchmindtree** [comment]
Congrats all :)

**Comment by cakecatz** [comment]
:tada:

**Comment by azilber** [comment]
Fantastic!  Now to recompile Piston...
