### ISSUE TITLE
Put "piston" as keyword on crates used by Piston

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#808]
https://crates.io/keywords/piston

Libraries that start with a "piston" prefix should add it as a keyword, plus smaller libraries that either requires a piston library or is strictly related to the game engine. This should be used as a looser way of referring to libraries used by or usable with the game engine.

**Comment by bvssvni** [comment]
List of repos that lacks the keyword "piston"

- [ ] [shader_version](https://github.com/PistonDevelopers/shader_version)
- [ ] [camera_controllers](https://github.com/PistonDevelopers/camera_controllers)
- [ ] [sprite](https://github.com/PistonDevelopers/sprite)
- [ ] [gfx_graphics](https://github.com/PistonDevelopers/gfx_graphics)
- [ ] [gfx_voxel](https://github.com/PistonDevelopers/gfx_voxel)
- [ ] [gfx-debug-draw](https://github.com/PistonDevelopers/gfx-debug-draw)
- [ ] [skeletal_animation](https://github.com/PistonDevelopers/skeletal_animation)
- [ ] [cam](https://github.com/PistonDevelopers/skeletal_animation)
- [ ] [piston_collada](https://github.com/PistonDevelopers/piston_collada)
- [ ] [window](https://github.com/PistonDevelopers/window)
- [ ] [glium_graphics](https://github.com/PistonDevelopers/glium_graphics)
- [ ] [input](https://github.com/PistonDevelopers/input)
- [ ] [event_loop](https://github.com/PistonDevelopers/event_loop)
- [ ] [glfw_window](https://github.com/PistonDevelopers/glfw_window)
- [ ] [wavefront_obj](https://github.com/PistonDevelopers/wavefront_obj)
- [ ] [fps_counter](https://github.com/PistonDevelopers/fps_counter)
- [ ] [texture](https://github.com/PistonDevelopers/texture)
- [ ] [vecmath](https://github.com/PistonDevelopers/vecmath)

**Comment by Potpourri** [comment]
I added to glfw_window.

**Comment by Potpourri** [comment]
I added to gfx_voxel.

**Comment by Potpourri** [comment]
I added to gfx_graphics.

**Comment by Potpourri** [comment]
I added to glium_graphics.

**Comment by bvssvni** [comment]
Done.
