### ISSUE TITLE
Create a library for ranges

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#811]
This will be useful for https://github.com/PistonDevelopers/piston/issues/786 but also for other stuff. It will be used for addressing thing. Operations will be done frequently on the `Range` type. I think offset/length is better for this purpose than start/end, because it does not have an inverse.

```Rust
pub struct Range {
    pub offset: uint,
    pub length: uint,
}
```

**Comment by bvssvni** [comment]
Created a new repo https://github.com/PistonDevelopers/range

**Comment by ruud-v-a** [comment]
How will this interact with slices? Essentially they are the same, right? It’s a fat pointer (though relative to the buffer).

**Comment by bvssvni** [comment]
It will not matter what it represents or whether the data is available. For example, it could be line numbers when parsing a file. It could be index operations where the data is stored in a database.
