### ISSUE TITLE
How to check for auto vectorization

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#817]
Posting this here since it might be useful later

See https://github.com/PistonDevelopers/image/issues/109#issuecomment-70377689

> `ndisassm <binary> | grep xmm`

**Comment by ruud-v-a** [comment]
Note that the use of the `xmm` registers does not really mean that the code has been vectorised, the compiler may use them as general-purpose registers if they are available anyway. For example, the `addss` (`_mm_add_ss` in C++, add single single-precision) instruction operates on `xmm` registers, but it only adds one component, the other three are passed through. A true vector add is `addps` (`_mm_add_ps` in C++, add packed single-precision).
