### ISSUE TITLE
How to organize information

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#834]
See https://github.com/PistonDevelopers/piston/issues/832#issuecomment-73199595

**Comment by bvssvni** [comment]
I'm in favor of using the issue tracker until we have something that lets people get notified, in case there is some important information. Another motivation is the search bar on Github, which lets you look up stuff easier than on the wiki.

**Comment by ruud-v-a** [comment]
I do think that the wiki is better suited to store and organise information, provided that it is kept up to date. A standalone Gollum instance does allow search, it’s a shame (and it surprises me) that GitHub does not have it, but of course you can always use your favourite search engine and append `site:https://github.com/PistonDevelopers/piston/wiki`. Using issues seems a bit incoherent to me.

Your problems are valid though. Have you tried asking GitHub about it? There does not seem to be a publicly available feature request database, but certainly more projects would benefit from such features.

**Comment by bvssvni** [comment]
I sent a message to Github using the contact form:

> In the Piston project we have a lot of issues labeled "Information" because the wiki pages does not have a search bar, so it is currently more practical to put it in the issue tracker. Is it possible to add a search bar to the wiki and can it be integrated with the repo search?
>
> Our open source organization is called "PistonDevelopers".
> Discussion: https://github.com/PistonDevelopers/piston/issues/834
>
>Thanks!

**Comment by bvssvni** [comment]
I got a response: It is added to Feature Request List.

**Comment by indiv0** [comment]
@bvssvni thanks for this!
