### ISSUE TITLE
Formal `GenericGraphics` semantics

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#836]
Don't know if this is possible, but I think it is worth investigating. This is for 2D and 3D.

An graphics API with the following properties:

* Easy to implement for different back-ends
* Has a simple set of core features
* Extensible
* Works across multiple threads
* Works without access to the device

It needs a set of core features to make libraries work on top of it, and it needs to be extensible to let people do what they want. In the Piston core we have `GenericEvent` which solves a similar problem for custom events from different window back-ends. The idea is to build something similar, but for graphics, and this requires a generic abstraction over side effects. We could try to develop some semantics, to see if it is possible to express this in Rust without performance overhead. Could use the same "objects as functions" method as used in Conrod https://github.com/PistonDevelopers/conrod/issues/223

### Pure functions

A pure function does not have side effects. For example, a matrix transformation:

```
transform(matrix) -> matrix'
```

### Side effect functions

An side effect function produces another function that operates on the side effect environment. In this case the side effect environment is the graphics device. For example, changing the model-view-projection:

```
mvp(x) -> (x'(graphics) -> graphics')
```

### Semi-pure functions

An semi-pure function requires some information from the graphics device before the value is known. It does not have side effects, but it is dependent on the state of the side effect environment. For example, when you render to a texture, the result can depend on the state of the graphics device:

```
x = texture, draw_commands
render_texture(x) -> (x'(graphics) -> x'')
```

### Impure functions

An impure function has a value depending on the side effect environment, but it also have an side effect. For example, creating a texture allocates memory on the device.

```
create_texture(x) -> (x'(graphics) -> x'', graphics')
```

### External resources

Every resource that the device has access to, must be "lifted" into a resource that can be operated on without accessing the device. For example, when an image from piston-image is converted to a texture for a graphics back-end, the same operation must be possible to do from the lifted image to the lifted texture.

```
tex(image, graphics) -> texture
lift(tex) -> (tex'(graphics) -> tex'', graphics')
```

One idea for immutable resources is to wrap them in `Arc<T>`.

An idea for mutable resources this requires a shared object which the graphics device knows, for example arrays that store 3D geometry. The operations on the shared object must then be lifted.

**Comment by bvssvni** [comment]
We could lift stuff using duck typing. The graphics state can be lifted to a phantom struct that wraps a `Vec` for the operations.

**Comment by bvssvni** [comment]
When altering the graphics state, one can use a list of draw commands. The same trick might work for other objects, except that the object depends on executing commands up a point.

Instead of different kinds of objects, one could use the same object for everything, but using phantom types to prevent operations that are invalid. The lifted object could have an interior reference counter that tells how many future commands depend on it.

```Rust
impl<T, U> GetFrom for (Lifted<U>, Lifted<T>)
    where
        (U, T): Pair<Data = U, Object = T> + GetFrom
{
    #[inline(always)]
    fn get_from(obj: &Lifted<T>) ->Lifted<U> {
        ...
    }
}
```

**Comment by bvssvni** [comment]
`SetAt` must also be implemented for `(U, Lifted<T>)`, where `T` implements a trait that maps to an associated `enum` through a static trait method. The `Lifted` type stores the `set` calls internally.

`ActOn` must be implemented for `(U, Lifted<T>)` that returns a lifted value. One can send in data but the returned value is lifted.

**Comment by bvssvni** [comment]
`SetAt` = side effect function
`GetFrom` = semi-pure function
`Action` = impure function

**Comment by kvark** [comment]
This is so crazy I don't believe I understand even 30%. Will re-read.

**Comment by bvssvni** [comment]
The problem is to create an asynchronous reference counter. A normal reference counter works by increasing the value when the object is used, decrease when it not used any longer, and free when it gets to 0. In an asynchronous reference counter, you want to tell "I am using these objects, and this is how many uses me it in the future". Instead of just a number, you need a list of the objects to decrease the counter, and if some command depends on it in the future, then it can't release them. When an object is passed that nobody are using, it can decrease the counter of the objects it uses.

**Comment by bvssvni** [comment]
One problem is that all commands that are sent must be known at the other end. Commands that operates on commands are not known.

**Comment by bvssvni** [comment]
Because the commands must be known at the device side of the asynchronous pipeline, this is not currently possible. Might work if Rust gets runtime reflection, but this won't happen anytime soon.

Closing.
