### ISSUE TITLE
Issue trying to build on windows7 (rust32/sdl32)

### ISSUE THREAD

**Issue by G4MR** [PistonDevelopers/piston#841]
Just to clarify using the 32bit version of rust and sdl since the tutorial is based on sdl:

Cargo.toml looks like so https://gist.github.com/G4MR/4186055317305ac58dc8

I get the following error 

    D:\Documents\Projects\Rust\SM>cargo build --verbose
        Updating git repository `https://github.com/PistonDevelopers/sdl2_window.git`
        Updating git repository `https://github.com/PistonDevelopers/opengl_graphics.git`
        Updating git repository `https://github.com/PistonDevelopers/piston.git`
        Updating git repository `https://github.com/PistonDevelopers/graphics.git`
        Updating git repository `https://github.com/PistonDevelopers/quack`
        Updating git repository `https://github.com/bjz/gl-rs`
        Updating git repository `https://github.com/AngryLawyer/rust-sdl2`
        Updating git repository `https://github.com/pistondevelopers/shader_version`
        Updating git repository `https://github.com/pistondevelopers/window`
        Updating git repository `https://github.com/pistondevelopers/input`
        Updating registry `https://github.com/rust-lang/crates.io-index`
        Updating git repository `https://github.com/pistondevelopers/event_loop`
        Updating git repository `https://github.com/tomaka/clock_ticks`
        Updating git repository `https://github.com/PistonDevelopers/freetype-rs.git`
        Updating git repository `https://github.com/pistondevelopers/texture`
        Updating git repository `https://github.com/pistondevelopers/image`
        Updating git repository `https://github.com/PistonDevelopers/freetype-sys`
        Updating git repository `https://github.com/PistonDevelopers/vecmath`
        Updating git repository `https://github.com/PistonDevelopers/read_color`
        Updating git repository `https://github.com/PistonDevelopers/interpolation`
        Updating git repository `https://github.com/rust-lang/num`
        Updating git repository `https://github.com/pistondevelopers/event`
    An unknown error occurred
    Process didn't exit successfully: `rustc - --crate-name - --crate-type dylib --crate-type bin --print-file-name` (status=101)
    --- stderr
    error: Unrecognized option: 'print-file-name'.

Not sure what's wrong, Cargo.toml looks like this:

    [package]
    name = "SM"
    version = "0.0.1"
    authors = [
        "Lamonte H"
    ]

    [[bin]]
    name = "SM"

    [dependencies.piston]
    git = "https://github.com/PistonDevelopers/piston.git"

    [dependencies.piston2d-graphics]
    git = "https://github.com/PistonDevelopers/graphics.git"

    [dependencies.pistoncore-sdl2_window]
    git = "https://github.com/PistonDevelopers/sdl2_window.git"

    [dependencies.piston2d-opengl_graphics]
    git = "https://github.com/PistonDevelopers/opengl_graphics.git"

Last but not least my rust version:

    D:\Documents\Projects\Rust\SM>rustc --version
    rustc 1.0.0-nightly (b63cee4a1 2015-02-14 17:01:11 +0000)

**Comment by G4MR** [comment]
Figured it out.  A long time ago I had Cargo installed manually before rust packaged cargo with rust so it was looking for the wrong version of cargo (I wonder how many errors I could have avoided).  Deleted the old cargo files and removed the old cargo path and fixed my issue.

**Comment by bvssvni** [comment]
@G4MR Thanks for sharing this! It might help other people getting a similar error message.
