### ISSUE TITLE
How to setup documentation for a repo

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#845]
http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

* How to update github pages with Travis CI

**Comment by Potpourri** [comment]
Just as option [rustdox](http://rustdox.com)
* `curl -X POST -H "Github: PistonDevelopers/piston" http://www.rustdox.com`

**Comment by bvssvni** [comment]
@Potpourri rustdox seems like a better solution, compared to set up a secure key for each repo.

**Comment by bvssvni** [comment]
An alternative is using  a script like this https://github.com/codahale/pcg/blob/master/deploy.sh

**Comment by bvssvni** [comment]
If https://github.com/gfx-rs/gfx-rs/pull/677 worked for Gfx, then the doc folder must be moved to the top folder in .travis.yml to host docs on Travis CI.

**Comment by Potpourri** [comment]
Currently rustdox broken, to us need other way to host docs.

**Comment by Potpourri** [comment]
I like [this approach](https://github.com/kmcallister/travis-doc-upload/blob/master/README.md).

**Comment by bvssvni** [comment]
I was just going to suggest that!

**Comment by bvssvni** [comment]
@Potpourri I added you to the Admin group.

**Comment by Potpourri** [comment]
Wow! Thank you! It's great to help me.

**Comment by bvssvni** [comment]
Should we create a repo for docs?

**Comment by Potpourri** [comment]
Yeah, I'll create 'docs' repo.

**Comment by Potpourri** [comment]
I done docs deploying for piston repo and update link to docs. For other repo's I'll do it tomorrow.

**Comment by bvssvni** [comment]
@Potpourri Nice! I'll help out tomorrow.

**Comment by bvssvni** [comment]
Done.
