### ISSUE TITLE
General Education Resources

### ISSUE THREAD

**Issue by stjahns** [PistonDevelopers/piston#846]
This is a dumping ground for any online educational resources, tutorials, or books that could be of use for Piston developers.

#### Links

- [Game Programming Patterns](http://gameprogrammingpatterns.com/contents.html) (Also available in print)

#### Texts

- [Game Engine Architecture](http://www.gameenginebook.com/) - Has some great sections on overall engine architecture, linear algebra from a game development perspective, graphics, animation, and more. Covers a little of everything in a reasonable amount of detail, an excellent launching point if you like giant hardcover books.

**Comment by faineance** [comment]
http://gameprogrammingpatterns.com/  
Free to read here http://gameprogrammingpatterns.com/contents.html but I would recommend you buy it in print or purchase the ebook.
