### ISSUE TITLE
Unable to get packages from source

### ISSUE THREAD

**Issue by snowe2010** [PistonDevelopers/piston#859]
Following the first few steps in the readme ends me up with this error. 
https://github.com/rust-lang/rustc-serialize/issues/89
I think the fix for right now is to make piston use 0.3.7

**Comment by snowe2010** [comment]
Looks like a better fix is to:

```
mkdir .cargo && echo 'paths = ["/home/username/rustc-serialize"]' > .cargo/config
```
In your project directory, then `cd $HOME` and 
```
git clone git@github.com:rust-lang/rustc-serialize.git
```
and then go back to your project and cargo build.

**Comment by bvssvni** [comment]
@snowe2010 Thanks for posting a work around! rustc-serialize seems to be updated now so that's why I guess you closed it.
