### ISSUE TITLE
1.0 Stability - Splitting work into master and unstable branches

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/piston#860]
This post was sparked by [Manishearth's comment on reddit](http://en.reddit.com/r/rust/comments/30mo6i/proposal_spend_most_of_the_beta_period_not/cptylmw).

It could be beneficial to maintain both a stable and unstable branch for the Piston repositories. A lot of crates depend on various parts of the Piston ecosystem, so it could be very beneficial to expose a stable, 1.0 compatible branch for each repository.

However, it is also true that there will likely be a continuous stream of interesting `feature`s that we will want to experiment with and incorporate into our libraries.

I suggest that we keep the `master` branches of each repository stable (no use of gated features) and have a separate `unstable` branch for unstable features and development. We would keep all crates.io crates synchronised with the `master` branch (so that they are always stable).

Thoughts? Think I'm going to spend the day trying to shake off feature gates in the RustAudio crates.

**Comment by bvssvni** [comment]
If everybody uses Rust nightlies then it doesn't hurt to keep some library 1.0 compatible, so either way it is safe to recommend using Rust nightly. You also have bugs that might be fixed on Rust nightly but triggers in an older 1.0 compatible version.

**Comment by bvssvni** [comment]
It would be nice with an overview of libraries that uses features.

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/piston/issues/861

**Comment by bvssvni** [comment]
Most projects are on stable now, and we could decide what to do per project for those who are not on stable Rust.

Closing.
