### ISSUE TITLE
`Float` is deprecated

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#864]
http://doc.rust-lang.org/std/num/trait.Float.html

Suggestions?

**Comment by bvssvni** [comment]
One idea is to copy the trait to a new library "float" and then add it as dependency to libraries such as vemcath.

**Comment by bvssvni** [comment]
Alternative is to use the ops traits `Add`, `Sub`, `Mul` etc. directly. This is the major usage.

To reduce code, one could add a trait `Ring` and `Field` that gets auto implemented from the operations, and then use those as constraints.

**Comment by bvssvni** [comment]
On second thought, there is no point having `Ring` for a library that is designed to use floats.

**Comment by mitchmindtree** [comment]
Woah, I didn't see this coming (for some reason I thought it was stable). The deprecation warning seems to suggest to use the [rust-lang/num crate](https://github.com/rust-lang/num) - perhaps the `Float` trait will get moved there?

**Comment by bvssvni** [comment]
I opened https://github.com/rust-lang/num/issues/74

**Comment by bvssvni** [comment]
The plan is to move the `Float` trait to the num library.

**Comment by bvssvni** [comment]
This is fixed in most libraries now, closing.
