### ISSUE TITLE
piston lacks an explanation of the game loop

### ISSUE THREAD

**Issue by KingOfThePirates** [PistonDevelopers/piston#870]
How do we go from
(c++, from http://gameprogrammingpatterns.com/game-loop.html)
```{c++, ignore}
double previous = getCurrentTime();
double lag = 0.0;
while (true)
{
  double current = getCurrentTime();
  double elapsed = current - previous;
  previous = current;
  lag += elapsed;

  processInput();

  while (lag >= MS_PER_UPDATE)
  {
    update();
    lag -= MS_PER_UPDATE;
  }

  render();
}
```
to using piston in our editor?

**Comment by bvssvni** [comment]
The game loop in Piston is:

```Rust
for e in piston::events(window) {
    use piston::event::*;

    if let Some(args) = e.update_args() {
        println!("{:?}", args.dt);
    }
}
```

**Comment by bvssvni** [comment]
You can adjust the update frame rate with

```Rust
for e in piston::events(window).ups(200) {
    ...
}
```

**Comment by bvssvni** [comment]
You can adjust the maximum frame rate with

````Rust
for e in piston::events(window).max_fps(30) {
    ...
}
```

**Comment by bvssvni** [comment]
The `piston::event::*` namespace contains all the event traits. They are implemented on top of `GenericEvent` which allows extending the game loop with new events. For example `RenderEvent`, `UpdateEvent`, `IdleEvent`, `PressEvent`, `ReleaseEvent`.

**Comment by bvssvni** [comment]
The game loop uses fixed time step for updates and render frames that "slips" if delayed. This makes it deterministic if the application code is deterministic in the update event. `args.ext_dt` in the render event can be used to smooth animations. `args.dt` in idle event tells you how many seconds it is expected to sleep, such that you can perform small background tasks in a single thread.

**Comment by KingOfThePirates** [comment]
A good tutorial would have you type your name, and it outputs it back to you in

1. cli
2. in it's own window that does it in font

and, a program that gives you three buttons: "square", "circle", and "triangle". You click a button, and it spins that shape. The buttons should be

1. traditional button
2. basic button that has no "UI" or "style" or smush-on-click, just a colored area, like a rectangle around the text

1 and 2 for each are different projects, but very similar

**Comment by bvssvni** [comment]
I wrote a blog post yesterday http://blog.piston.rs/2015/04/07/piston-0.1/

It is already outdated :P

**Comment by KingOfThePirates** [comment]
What is outdated? I'm about to learn it.

**Comment by bvssvni** [comment]
@KingOfThePirates This has changed:

```Rust
use piston::event::Events;

for e in window.events() {
    ...
}
```

**Comment by KingOfThePirates** [comment]
So reading that blog would, at the moment, not be beneficial for me?

**Comment by bvssvni** [comment]
@KingOfThePirates It contains some other useful information, it is just the example code that is outdated, but it still illustrates the point.

**Comment by KingOfThePirates** [comment]
When will it be up-to-date, do you think?

**Comment by bvssvni** [comment]
I'll probably write a new one when things settles down a bit.

**Comment by KingOfThePirates** [comment]
Okay, I have plenty of other programming books to read until then :D

**Comment by bvssvni** [comment]
@KingOfThePirates And I have plenty of One Piece episodes to watch! What's your favorite character? Oh, nevermind...

**Comment by KingOfThePirates** [comment]
:)

**Comment by bvssvni** [comment]
@KingOfThePirates I like Nico Robin, because she is dark in some subtle ways, like never telling there is a danger ahead despite being the one on watch. I think it is interesting to give a character life by ways the character doesn't do in certain situations.

Btw, things changes so frequently that if I put much effort into documentation now, I'll have to rewrite it later. The example on the webpage has broken many times even I thought it was the final one each time. Better fix other things for now.

**Comment by KingOfThePirates** [comment]
Write a program that writes the document. Put each section in it's own routine. Make sure to put the parts that are likely to change in a separate class. Then you almost never have to write it again.

**Comment by KingOfThePirates** [comment]
main
```
let some_file = copy_text("some_file.txt");
let some_other_file = copy_text("some_other_file.txt");
...

let intro = create_section(some_file);
let getting_started = create_section(some_other_file);
...

write_on_page(intro);
write_on_page(getting_started);
write_on_page(what_is_piston_core);
write_on_page(piston_programs_with_events);
write_on_page(how_does_piston_use_graphics);
write_on_page(other_projects);
```

**Comment by KingOfThePirates** [comment]
main
```
let some_file = copy_text("some_file.txt");
let some_other_file = copy_text("some_other_file.txt");
...

let intro = create_section(some_file);
let getting_started = create_section(some_other_file);
...

write_on_page(intro);
write_on_page(getting_started);
write_on_page(what_is_piston_core);
write_on_page(piston_programs_with_events);
write_on_page(how_does_piston_use_graphics);
write_on_page(other_projects);
```

**Comment by bvssvni** [comment]
Closing since the original question was answered.
