### ISSUE TITLE
Make it `for e in window.events() { ... }`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#872]
@kvark got this idea:

```Rust
for e in window.events() {
    ...
}
```

**Comment by Potpourri** [comment]
I like it. :+1: Add `events` to `Window` trait?

**Comment by kvark** [comment]
If your window should be a separate thing from the events, you can try having a `WindowExt` trait of sorts either in the events crate or some other place that knows about both windows and events.

**Comment by Potpourri** [comment]
We already have three `*Window` traits, I think not worth create fourth.

**Comment by bvssvni** [comment]
One problem is that the `Window` trait lives in pistoncore-window while `Events` live in pistoncore-event_loop.

**Comment by kvark** [comment]
@bvssvni that's why I mentioned `WindowExt`. It can live in a a crate that knows about both events and windows and glue them together. Perhaps, `piston` is such a crate?

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/event/pull/352

Since we import `piston::event::*;` anyway the solution @Potpourri came up with is elegant.

```Rust
use piston::event::Events;
// use piston::event::*; // also imports the event traits

for e in window.events() {
    ...
}
```
