### ISSUE TITLE
Information related to OpenGL context creation

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#878]
Collect some information to help setup context creation correctly with forward-compatible and core flags sets right for different platforms.

https://www.opengl.org/wiki/Core_And_Compatibility_in_Contexts

https://github.com/cmr/nice_glfw/blob/master/src/lib.rs

- @cmr attempts at initializing this correctly for GLFW

**Comment by bvssvni** [comment]
Running nice_glfw's "simple" example:

OSX 10.9.5: `OpenGL Version: 3.3 NVIDIA-8.24.16 310.90.9.05f01`

Then I tried commenting out forward-compat and core hints:

```Rust
.try_hints(&[
            WindowHint::ContextVersion(3, 2),
            // WindowHint::OpenglForwardCompat(true),
            // WindowHint::OpenglProfile(OpenGlProfileHint::Core),
        ])
```

When one of them is commented, I get 2.1. Both are required to get 3.2.

**Comment by bvssvni** [comment]
@KingOfThePirates Do you mind testing this on your platform?

**Comment by KingOfThePirates** [comment]
What to you want me to comment out exactly?

**Comment by KingOfThePirates** [comment]
And when I try to do `cargo run --example simple` it can't find an example target.

**Comment by fkaa** [comment]
@KingOfThePirates the example is in its own project so you have to cd into it and `cargo run`

**Comment by KingOfThePirates** [comment]
Oh jesus I'm stupid

**Comment by fkaa** [comment]
Output for me with this

```
OS X 10.10.2
MBPro 13" Mid '12
Intel HD 4k
```

```rust
[], [ContextVersion(4, 1)]
Couldn't create a context for hints [] and [ContextVersion(4, 1)]

[], [ContextVersion(4, 1), OpenglProfile(Core)]
Couldn't create a context for hints [] and [ContextVersion(4, 1), OpenglProfile(Core)]

[], [ContextVersion(4, 1), OpenglForwardCompat(true)]
Couldn't create a context for hints [] and [ContextVersion(4, 1), OpenglForwardCompat(true)]

[], [ContextVersion(4, 1), OpenglForwardCompat(true), OpenglProfile(Core)]
Created GLFW window with GL context hints [] and [ContextVersion(4, 1), OpenglForwardCompat(true), OpenglProfile(Core)]

OpenGL Version: 4.1 INTEL-10.2.46
```

**Comment by KingOfThePirates** [comment]
No matter what I uncomment or if I leave the file unchanged, it has no cli output, and it opens a window and instantly closes it.

**Comment by KingOfThePirates** [comment]
I'm off to work. Will delete this reply and continue with this the next time I can come on (probably tomorrow).

**Comment by bvssvni** [comment]
@KingOfThePirates It should print something out to the console. That's all.

**Comment by KingOfThePirates** [comment]
It looked like a normal successful run. Said `running ...`, and that was it.

**Comment by bvssvni** [comment]
@KingOfThePirates When running I get a text output to the console like this:

`OpenGL Version: 3.3 NVIDIA-8.24.16 310.90.9.05f01`

**Comment by KingOfThePirates** [comment]
Then something is wrong with mine. We have to wait until tomorrow to get more information with my platform.

**Comment by KingOfThePirates** [comment]
I can't get it to do anything else. I don't have OS X btw.

Output and call stack:
```bash
me@me-desktop ~/nice_glfw/examples/simple $ cargo run -v
       Fresh khronos_api v0.0.5
       Fresh glfw-sys v3.1.2
       Fresh semver v0.1.19
       Fresh libc v0.1.6
       Fresh bitflags v0.1.1
       Fresh log v0.3.1
       Fresh gl_common v0.0.4
       Fresh xml-rs v0.1.23
       Fresh glfw v0.0.7
       Fresh gl_generator v0.0.23
       Fresh nice_glfw v1.0.1 (file:///home/me/nice_glfw/examples/simple)
       Fresh gl v0.0.12
       Fresh simple v0.0.1 (file:///home/me/nice_glfw/examples/simple)
     Running `target/debug/simple`
me@me-desktop ~/nice_glfw/examples/simple $ RUST_BACKTRACE=1 ./target/debug/simple
me@me-desktop ~/nice_glfw/examples/simple $
```
