### ISSUE TITLE
Start stabilizing stuff!

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#881]
Recently I have been thinking that providing stable APIs are more important than pretty much every other concern in software development if you want to use them commercially, but also to stop reconsider things that already have been thought of. Once you reach a certain level of quality, you start running into tradeoffs like "should `WindowSettings` contain the `OpenGL` flag, how will this work with the future `Vulkan` flag etc.".  And then you figure out that the reason those are separated already is a good choice, but you can't make it nicer without also making the writing of back-ends more complicated.

Another example, when we try "fleshing out" APIs with things you think will be nicer and prettier for the user, you often end up with dependency issues like library A need to depend on library B even A only needs a small part of B. It is very hard to communicate the reasons why things are like they are, even to your future self. Making a library stable is an efficient way of preventing yourself on working something that probably is a waste of time.

Therefore, I think Piston would benefit from a period where we go through the basic stuff and mark things as stable that we don't want to change, even with the risk that we will do some mistakes or it doesn't end up perfect. We could write down why we think it won't change, label it as "Information" such that people can find it later.

This stabilization procedure doesn't have to be final before a 1.0 version of library, but I believe will save time in total by start doing this now.

**Comment by mitchmindtree** [comment]
:+1:

I think another really good move towards offering a stable API is being consistent with publishing to crates.io so that users can take advantage of the Cargo.lock (it can be a bit scary when there are only git deps to work with).

**Comment by bvssvni** [comment]
@mitchmindtree I think Cargo.lock works with git commits, but you are right about publishing to crates.io.

I've started adding people as owners that ask for updating the version on crates.io. Maybe I should go through all the repos and add people that I suspect will need the access in the future.

**Comment by bvssvni** [comment]
Thread about using stability attributes in user crates: http://users.rust-lang.org/t/using-stability-attributes-in-user-crates/955

It seems we can't use them for now and need some other way to track the progress.

**Comment by bvssvni** [comment]
One problem we had with vecmath was the dependency on the `num` crate which contains a lot of stuff. The only thing we were using it for was to write generic code over floats. There is a new library https://github.com/pistondevelopers/float which contains traits for float, such that some subset of the Piston ecosystem gets more stable. Not an ideal solution, but we'll see what happens after Rust 1.0.

I'll close this discussion because most things are settled now, and I'll open up issues on the specific projects where I want some changes.
