### ISSUE TITLE
Merge piston_window into gfx_graphics

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#890]
Currently we have a problem where gfx_graphics requires piston_window for the examples, while piston_window requires gfx_graphics. See https://github.com/PistonDevelopers/gfx_graphics/issues/236

We could  move the stuff into gfx_graphics and rename `PistonWindow` to `GfxWindow`. The same convenience pattern can be done for glium_graphics, which already has a `GliumWindow` object.

This will solve the problems with circular dependencies. piston_window would then be deprecated.

**Comment by bvssvni** [comment]
`GfxWindow` will be back-end agnostic, so you can use it for any window back-end.

**Comment by kvark** [comment]
O_o this is a bit controversial. I'm not convinced (yet?) that piston_window is the right design with its recursive nature, and it would surely be not obvious to find it inside gfx_texture if it's moved.

**Comment by bvssvni** [comment]
@kvark I think you meant gfx_graphics?

The recursive nature comes from the idea that you only need to pass around one object, and this object is also capable to running a nested game loop.

**Comment by bvssvni** [comment]
I think this could wait until we have tested the piston_window design. Closing.
