### ISSUE TITLE
Move libraries to crates.io

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#891]
This is an experiment to see how using crates.io works out for Piston, in order to figure out what potential problems there are. Edit this comment to create a list of updated libraries:

Complete:
- [x] input (@aepsil0n)
- [x] viewport (@bvssvni)
- [x] event_loop (@bvssvni)
- [x] event (@bvssvni)
- [x] window (@aepsil0n)
- [x] piston (@bvssvni)
- [x] float (@bvssvni)
- [x] interpolation (@mitchmindtree)
- [x] vecmath (@mitchmindtree)
- [x] graphics (@mitchmindtree)
- [x] gfx_text (@Kagami)
- [x] gfx_texture (@mitchmindtree)
- [x] glium_graphics (@aepsil0n)
- [x] glutin_window (@mitchmindtree)
- [x] glfw_window
- [x] sdl2_window (@aepsil0n)
- [x] drag_controller (@bvssvni)
- [x] collada (@stjahns)
- [x] dual_quaternion(@stjahns)
- [x] gfx_debug_draw (@stjahns)
- [x] dev_menu (@stjahns)
- [x] skeletal_animation (@stjahns)

Remaining:
- [x] opengl_graphics (@mitchmindtree) ([needs merge and publish](https://github.com/PistonDevelopers/opengl_graphics/pull/178))
- [x] gfx_graphics [PR waiting on piston_window](https://github.com/PistonDevelopers/gfx_graphics/pull/245)
- [x] piston_window ([needs publish](https://github.com/PistonDevelopers/piston_window/issues/36))
- [x] conrod (depends on piston_window and gfx_graphics)

**Comment by aepsil0n** [comment]
:+1:

I'll start with `window`. Can't update the top-post though.

**Comment by LaylConway** [comment]
:+1:
I would like to ask if `text` and `gfx_texture` could be moved to crates.io as well.

**Comment by bvssvni** [comment]
@LaylConway Those might wait for Gfx 0.6.

**Comment by LaylConway** [comment]
I don't think it will be needed to wait until gfx hits 0.6, the latest version is already on crates.io.

**Comment by LaylConway** [comment]
I've pushed gfx_text to crates.io following the way other gfx_* crates have been published. I made a fork and applied changes to the dependencies to use the crates.io versions. I still need to add owners, I tried to add kagami but he did not log into crates.io yet so I can't add him yet.

**Comment by Kagami** [comment]
@LaylConway thanks. Logged.
Pushed v0.1.0 tag to git with updated Cargo.toml: https://github.com/PistonDevelopers/gfx_text/tree/v0.1.0

**Comment by bvssvni** [comment]
@LaylConway can you add me as owner?

**Comment by bvssvni** [comment]
Commenting git links is not that useful now that you can find the links on crates.io. I think we should switch to use `[dependencies]` instead of `[dependencies.foo]`.

**Comment by bvssvni** [comment]
@LaylConway It is a bit annoying to use git dependencies to Gfx now, for example the piston-graphics crate uses the Gfx draw_state library and can't be used as a crates.io dependency because of that. However, Gfx hits 0.6 very soon and we can switch at the same time.

**Comment by Kagami** [comment]
>for example the piston-graphics crate uses the Gfx draw_state library and can't be used as a crates.io dependency because of that

But stable gfx-rs uses draw_state from git and it was somehow published to crates.io: https://github.com/gfx-rs/gfx-rs/blob/839f810f7dfdecb3bd68cc558a968bfaeb4d29e7/Cargo.toml#L30

**Comment by LaylConway** [comment]
@bvssvni Any gfx crates that are already (recently) published to github are using crates.io dependencies already, but it seems draw_state is just not one of them yet. Might be useful to bring that up with @kvark since there doesn't seem to be a reason it can't be pushed the same way other parts of Gfx were. The switchover does indeed seem to be 0.6 though, I have no problem waiting for that with the crates that are currently published already.

**Comment by LaylConway** [comment]
@Kagami Git versions of Gfx libraries don't quite match the crates.io ones, the difference is that the dependencies are changed to use crates.io dependencies. draw_state is an exception as it hasn't been updated in a while.

**Comment by LaylConway** [comment]
I've just now added @bvssvni and @Kagami as owners to gfx_text's crate.

**Comment by mitchmindtree** [comment]
[gfx-rs 0.6 landed!](https://crates.io/crates/gfx) Looks like we can start updating all the stuff with gfx deps :tada: I'm a bit busy right now but might be free to start later tonight.

**Comment by mitchmindtree** [comment]
Ok, mainly just waiting on [an update](https://github.com/PistonDevelopers/gfx_graphics/issues/244) for gfx_graphics before tackling the rest now :)

**Comment by bvssvni** [comment]
Done.
