### ISSUE TITLE
Bump "0.0.x" libraries to "0.1.0"

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#894]
The rule in semantic versioning is that two libraries are compatible if they have the same first non-zero number, which means that "0.0.x" is special since every new version breaks. If we bump them to "0.1.0" then we can use "0.1.x" to specify a minimum version that will make minor breaking changes smoother, for example in parts that is less used in the API but only used by a library. If there are large breaking changes, we bump the "0.x" version. Do not use "0.0.*" because that makes Cargo think it compatible with any version, instead we want to use a minimum version.

**Comment by bvssvni** [comment]
- [x] graphics (@bvssvni)

**Comment by kvark** [comment]
:+1:

**Comment by bvssvni** [comment]
We'll use a gist this time to try to not overwrite each other changes https://gist.github.com/bvssvni/0bf9d468e1529bb79778

**Comment by bvssvni** [comment]
There is no UI for merging gists, so we could use the "#piston-internals" chat room on IRC and I can edit the gist to keep it updated.

**Comment by bvssvni** [comment]
Alternative leave a comment on the gist.
