### ISSUE TITLE
Add a `find_assets` function somewhere for finding the assets directory.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/piston#896]
An `assets` directory is used many places throughout the ecosystem and often the path is hardcoded, meaning the user must run the built program from a specific directory which can be quite annoying. It would be nice to have a `find_assets` function that would search parent directories for the `assets` directory. A rough example is below.

```Rust

// Find the assets folder by checking parent directories.
fn check_for_assets(depth: u8, path: &Path, target: &mut PathBuf) -> ::std::io::Result<()> {
    if ::std::fs::metadata(path).unwrap().is_dir() {
        for entry in try!(::std::fs::read_dir(path)) {
            let entry = try!(entry);
            let entry_path = entry.path();
            if entry_path.ends_with("assets") {
                *target = entry_path;
                return Ok(());
            }
        }
    }
    if depth > 0 {
        if let Some(parent) = path.parent() {
            try!(find_assets(depth - 1, &parent, target));
        }
    }
    Ok(())
}

/// API function for the user to call, returns the path to the assets folder as a PathBuf.
fn find_assets(recursion_depth: u8) -> PathBuf {
    let mut font_path = PathBuf::new();
    let cwd = ::std::env::current_dir().unwrap();
    check_for_assets(recursion_depth, &cwd, &mut font_path);
    font_path
}

fn main() {
    let font_path = find_assets(4).join(Path::new("NotoSans/NotoSans-Regular.ttf"));
}

```

In which crate should we put such a function? Perhaps its own? Maybe there is already something better available on crates.io?

**Comment by bvssvni** [comment]
This would be nice!

**Comment by bvssvni** [comment]
It could be `find_folder(name, max_parents)` and then we could have a generic find_folder library.

**Comment by mitchmindtree** [comment]
:+1:

Also, perhaps the `depth` could be an `i8` where positive depths walk into the directory tree and negative depths step out and check parent directories?

**Comment by bvssvni** [comment]
Or we could have `(i8, i8)` or a struct to support both.

**Comment by mitchmindtree** [comment]
Perhaps an enum?

enum Search {
    Parents(u8),
    Kids(u8),
    Both(u8, u8),
}

**Comment by bvssvni** [comment]
Yeah, that would be nice.

**Comment by mitchmindtree** [comment]
I can do this, I've got a start going.

I'll add a repo to PistonDevelopers called `find_folder`

**Comment by bvssvni** [comment]
I'll set up labels and add teams when the repo is created.

**Comment by mitchmindtree** [comment]
https://github.com/PistonDevelopers/find_folder

**Comment by mitchmindtree** [comment]
Alright, all done and published to crates.io! @bvssvni I've added you as an owner :balloon: If anyone else wants to be added as an owner let me know. Closing this!
