### ISSUE TITLE
Move core libraries to the "piston" repo

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#902]
See Gfx moving some libraries to a single repo https://github.com/gfx-rs/gfx/issues/768.

Currently the piston repo is just a tiny library reexporting "input", "event" and "window". I have received feedback from various people finding the decoupled structure of Piston to be confusing. One source of confusion seems to be the organization of repos. The Piston core have a similar history to the Gfx library except the problem was more experimenting in design and the need for working on separate libraries. Now the core is more stable we could move them together again, and this will have no consequences since we use crates.io dependencies internally.

**Comment by Esption** [comment]
This is specifically aimed at `input`, `event`, and `window` then?

Personally, I think that things such as `*_window` / `*_graphics` things should be moved into the base project at the very least (`window` and `graphics` respectively), and then be able to use `#[cfg()]` on them so you only compile in what's needed, as I believe that's part of the reason to have them separated, right?  It seems a bit unnecessary to have them split up when Rust's cfg flags could do it nicely without a hard split of the repos.

Just my thoughts.  Anyway yeah, I'd be in support of a bit of consolidation of the repos.  :+1:

**Comment by bvssvni** [comment]
The idea is to keep the same crate structure, but move `input`, `event` and `window` into the `piston` repo. The dependency graph will stay the same. We can improve it without changing the architecture.

It might be a good idea to keep the window back-ends and the core separate, as back-ends are more unstable. The 2D graphics libraries should stay decoupled from the core.

We do not have the same problem here as with Gfx, where changes happens frequently across the libraries. I don't think users have problem understanding back-ends, but what makes it confusing is that Piston has both back-ends and a modular core. The problem is users being confused by the organization, because the core is spread across multiple repos, so they mix it up with the back-ends. The core does not change frequently, but the other libraries do and sometimes simultaneously, so it is more to gain by keeping the stuff evolving in parallel from each other.

**Comment by mitchmindtree** [comment]
@bvssvni +1 :+1:
