### ISSUE TITLE
Add crates.io version buttons to READMEs

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#910]
See https://github.com/PistonDevelopers/meta

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston/pull/911

**Comment by jeremija** [comment]
Should sub crates' `README.md` files also show to the same buttons pointing to `PistonDevelopers/piston`?

[![Build Status](https://travis-ci.org/PistonDevelopers/piston.svg)](https://travis-ci.org/PistonDevelopers/piston)[![Crates.io](https://img.shields.io/crates/v/piston.svg?style=flat-square)](https://crates.io/crates/piston)

**Comment by bvssvni** [comment]
Yes.
