### ISSUE TITLE
How to install FreeType

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#912]
#### Freetype on OS X

With [Homebrew](http://brew.sh), install freetype with

```
brew install freetype
```

With [MacPorts](https://www.macports.org), install freetype with

```
sudo port install freetype
```

Alternatively, download directly from http://www.freetype.org/download.html

#### Freetype on Ubuntu
If you are on Ubuntu, you can run

```
sudo apt-get install libfreetype6-dev
```

#### Freetype on Windows
See https://github.com/PistonDevelopers/freetype-sys#for-windows-users

**Comment by anmej** [comment]
I suggest you add this, or link to this, to the readme.

**Comment by bvssvni** [comment]
@anmej It is, look for "How to install FreeType".

**Comment by TheRealHnefi** [comment]
The Windows howto is outdated or broken in a couple of ways. The required zlib link, which goes via the GTK project for some reason, ultimately ends up in a 404. Also, even after the instructions have been followed, attempting to build piston via "cargo build" ends with a linker error:
note: ld: cannot find -lfreetype-6

Frankly, I think it would be better to just link to a how-to for building FT and zlib on Windows, along with a proper guide on how to point Cargo to the resultant .dll files. Adding the linked .cargo/config to the project or the user home directory doesn't seem to work.

**Comment by bvssvni** [comment]
@TheRealHnefi Could you open up a new issue on this?

**Comment by TheRealHnefi** [comment]
@bvssvni Sure. Opened issue 969.

**Comment by KritR** [comment]
Should we add something for MacPorts ? 

With [MacPorts](https://www.macports.org), install freetype with

```
sudo port install freetype
```

**Comment by bvssvni** [comment]
@KritR Thanks! Added.

**Comment by Muzz** [comment]
The links for 32 and 64 bit freetype windows are broken and go to 404 pages.
