### ISSUE TITLE
Resources for making 2D RPG games

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#930]
* [Pixel art tutorials](http://www.pixelprospector.com/the-big-list-of-pixel-art-tutorials)
* ["How to prototype a Game in Under 7 Days"](http://www.gamasutra.com/view/feature)/2438/how_to_prototype_a_game_in_under_7_.php
* [Danc's Miraculously Flexible Game Prototyping Tiles](http://www.lostgarden.com/2007/05/dancs-miraculously-flexible-game.html)

**Comment by viperscape** [comment]
I started tinkering with [this](https://github.com/viperscape/rpg/blob/master/src/main.rs) months back, haven't worked on it in a while but perhaps useful for discussion

**Comment by timClicks** [comment]
Maybe I should add this as a new question/issue, but is there a standard way to distribute games made in `piston` to end users.. particularly on Windows? That is, I don't want them to have to bother with needing to manually install Rust/SDL/whatever. I just want to enable them to click a .exe and for it to start up.

**Comment by bvssvni** [comment]
@timClicks Can you open this in a new issue? There has not been any discussion about this and it's time to think about it.

**Comment by timClicks** [comment]
@bvssvni Thanks, #996 opened.
