### ISSUE TITLE
Create a plugin/mod management tool

### ISSUE THREAD

**Issue by fenhl** [PistonDevelopers/piston#936]
As previously discussed, the [Hematite](http://hematite.piston.rs/) project will benefit from this.

I will create the [inventory](https://github.com/PistonDevelopers/inventory) repo, the name has been suggested by dwins on IRC.

**Comment by bvssvni** [comment]
Nice! I'll add labels and the teams when you have created the repo.

**Comment by fenhl** [comment]
Repo is live, will open issues about further design discussion there.
