### ISSUE TITLE
Add `default-features = false` for `num` dependency in pistoncore-input

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#940]
The input library currently depends on `num` and `rustc_serialize`. The `num` crate is needed for the `FromPrimitive` trait. This is used to convert from SDL2 key codes.

By adding `default-features = false`, the dependency graph for `num` will become simpler.

**Comment by zummenix** [comment]
Recently I discovered that by adding `default-features = false` for `num` simplifies the dependency graph. Just note, don't know if it helps in this issue.

**Comment by bvssvni** [comment]
There seems to be a problem when writing a new window back-end if there are no key codes.

For example, what does `Key::Quote` mean? If it does not have a value then how do you know which button it is on your keyboard? Using an SDL key code makes it easy to solve such cases without needing to test against one of the exiting window back-ends.

**Comment by bvssvni** [comment]
Adding `deafult-features = false` sounds like a good idea.
