### ISSUE TITLE
Joystick/Controller/Gamepad design

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#943]
I'd like to have a cross platform library for user input (https://github.com/PistonDevelopers/piston/issues/884), but it would be nice if both separate libraries and window back-ends could integrate with the event model. There are platforms where controllers are the major way of interacting, and this must be supported by widget frameworks.

pistoncore-input could have some structures similar to the design in SDL2. SDL2's way of dealing with this is to send an event when a device is connected or disconnected. Each input device is assigned an id and has buttons and axis states (absolute).

Alternative is Steenberg's Betray https://github.com/PistonDevelopers/input/issues/20 which seem well thought out. This unites multi-touch with controllers. Could be used in a cross platform API.

I think that button presses could be used with `PressEvent`. In many cases you want to handle the button events separately from the axis motion. This integrates nicely with the event model.

* An event model based on SDL2, integrated with the current design
* A cross platform API based on Betray, with functions for mapping to the event model

**Comment by bvssvni** [comment]
One idea is to use a simple number for the buttons.

* Orientation of the device can change. When the buttons are attached to the device, the semantics of Left/Right/Up/Down changes.
* The controller can be designed to change orientation, meaning that the semantics of Left/Right/Up/Down also changes.

**Comment by bvssvni** [comment]
It is always a good idea  keeping events orthogonal.

* Make writing window back-ends as simple as possible, with keeping as little state as possible.
* Transformations should be done per application whenever possible. Don't emulate other events using other events if you can avoid it. This makes it difficult to spot bugs and makes it more complicated to reason about the event handling.

**Comment by xaviershay** [comment]
> Make writing window back-ends as simple as possible, with keeping as little state as possible.

Intuitively I feel like this is the wrong emphasis. Shouldn't we be optimising for the game developer? Why is state in the window bad? (Hrmm ... could we pull the state up to a common piston level?)

> Transformations should be done per application whenever possible.

In general this seems reasonable, I guess we need to sort out the prior point before discussing though :) In this instance, it's not really "emulation" since the events can *only* be synthetically generated. It's much easier to use for most types of games ("I'm moving something around the screen!"), and if anyone needs anything more complicated they can simply "drop down" to the raw events.

A relevant parallel seems generating keypress events - SDL2/piston send repeated keypress events as a convenience when the same key is being held down. (I'd argue that this behaviour is the type you _don't_ want - since it's "overloading" an existing event rather than using a different one such as `KeyRepeat`.)

**Comment by xaviershay** [comment]
Just realised some extra context that might help explain different opinions: the device I'm testing with is a [USB gamepad](http://www.amazon.com/Buffalo-Classic-USB-Gamepad-PC/dp/B002B9XB0E/ref=sr_1_2?ie=UTF8&qid=1443373599&sr=8-2&keywords=usb+snes+controller). Note it's not actually a joystick in the traditional sense - it has a DPad - but it reports as one. I wonder how common that is? That would influence the API design.

**Comment by bvssvni** [comment]
Yeah, I was looking up an image of the gamepad. I have a PS3 controller that can be connected to my Mac.

**Comment by bvssvni** [comment]
States are usually bad, not because it could be more convenient, but because when it's convenient. When you write one feature, you don't want it to interfere with other features.

For example, when you send mouse coordinates with button events, or do relative mouse coordinates with mouse position, it doesn't work that well with different features like mouse capture. It is really hard to explain this, but over and over after a lot of thinking we come to the same conclusion: Keep as little state as possible.

I don't like to argue over general assumptions, and keeping little state is one of the few in the piston core. Let's go through the detail and figure this out together.

**Comment by xaviershay** [comment]
ok, I'll trust you on that :) Thanks for helping me understand. Will add in the axis events, remove the state, and see how things look.

**Comment by xaviershay** [comment]
> A relevant parallel seems generating keypress events

I was flat wrong here, keypress events do not autorepeat. Apologies, I must have been thinking about a different library in my past.

**Comment by bvssvni** [comment]
I was curious about the key repeat, because I couldn't remember it.

**Comment by bvssvni** [comment]
Suggestion for structs:

```Rust
pub struct JoystickButton {
    pub id: i32,
    pub button: u8
}

pub struct JoystickAxisArgs {
    pub id: i32,
    pub axis: u8,
    pub value: f64
}
```

**Comment by xaviershay** [comment]
`s/value/position/` for the args struct, seems clearer.

**Comment by bvssvni** [comment]
I usually think of 2D or 3D when reading `position`, but now I think about it, I like it better than `value`.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/piston/pull/978
