### ISSUE TITLE
Can't programmatically close windows.

### ISSUE THREAD

**Issue by RDeckers** [PistonDevelopers/piston#944]
Currently (as far as I can see), there is no public function to tell a window to close. We can bind on escape, and obey normal close events such as alt-f4 and the close button but there is no function we can call to easily set  the "should_close" variable currently used. 

When running in fullscreen or borderless mode, pressing the close button is not an option. Closing on esc is not good UX as many games bind escape to pause/open-menu, so it is not expected behaviour for many users.

Currently, to implement a custom exit screen we'd have to explicitly break out of the event loop, but this unnecessary as the event-loop itself already checks for a "should_close"  bool.

**Comment by bvssvni** [comment]
Thanks for the input!

Writing a custom exit screen is a good point. This is a use case where you want to signal to the window that it should close.

**Comment by bvssvni** [comment]
I suggest adding `AdvancedWindow::set_should_close`, since `Window` is the minimum for getting the game loop working.

**Comment by RDeckers** [comment]
I have a local fork with the necessary changes (Added to the trait, and the various window implementations), shall I go ahead and issue a pull request?

**Comment by bvssvni** [comment]
@RDeckers That would be nice!

**Comment by RDeckers** [comment]
Should it go in `AdvancedWindow::set_should_close` though? Personally, I feel it would be better in `Window::set_should_close` as window already implements a `should_close(&self) -> bool` function and the event loop. And all current back-ends do what is basically `if !should_close { ... } else None` in their event loop.

I would consider this basic functionality, but it's your call :)

**Comment by bvssvni** [comment]
I'm OK with adding it to `Window`.
