### ISSUE TITLE
Delete deprecated window/input/event_loop repos

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#967]
These repos are deprecated, because they are moved into the piston repo, and will be deleted in one week from now:

- [ ] https://github.com/pistondevelopers/input
- [ ] https://github.com/pistondevelopers/window
- [ ] https://github.com/PistonDevelopers/event
- [ ] https://github.com/pistondevelopers/event_loop

**Comment by bvssvni** [comment]
Maybe we should not delete them yet, since there are issues that are still useful.

**Comment by bvssvni** [comment]
One solution is to move the stuff we'd like to keep to the wiki, but this will take a lot of work and the information is not searchable.

**Comment by caspark** [comment]
Are you primarily concerned about open issues, or specific issues (like the existing ones which list features), or closed issues to give context to git history?

**Comment by bvssvni** [comment]
There are some open issues that are still relevant, but those could be moved without much effort. Another problem is discussions, but those could be evaluated/summarized by case. The biggest concern is the closed issues, that are most valuable in the long term.

**Comment by bvssvni** [comment]
I think we should wait with this. Closing.
