### ISSUE TITLE
Windows howto is outdated

### ISSUE THREAD

**Issue by TheRealHnefi** [PistonDevelopers/piston#969]
Attempting to follow the Windows howto leads to a couple of issues. Using Rust 1.2 on Windows 7, I ran into the following problems:

1: The linked zlib and Freetype libraries. The 32-bit zlib library link from the GTK page leads to a 404, and it's not immediately obvious which versions of each library should be used (the GTK page lists several versions of each library). It would be better if the proper versions were hosted by Piston or a link to instructions on how to compile both libs on Windows.

2: Even after adding a .cargo directory with the properly laid out config, the linker is unable to find the Freetype and zlib libraries.

3: After working around issue 2, I managed to compile the howto sample program. However, the program crashed on init (or panics, I suppose; it immediately exits with a large negative number as result). Attempting to add a debug printout immediately after main failed; only after removing the definition and references to the App structure does the program not crash.

**Comment by bvssvni** [comment]
Updated with link to the freetype-sys README, which points to prebuilt binaries https://github.com/PistonDevelopers/binaries. Reopen if there is still a problem.

**Comment by philippotto** [comment]
@TheRealHnefi In step 3 you say "after working around issue 2...". How did you work around it? I followed the README at https://github.com/PistonDevelopers/freetype-sys, but still get the following error:

`ld: cannot find -lfreetype`

I tried the -pc-windows-gnu as well as the -pc-windows-msvc part, but neither did work.
