### ISSUE TITLE
A crate for `Gesture` events.

### ISSUE THREAD

**Issue by mitchmindtree** [PistonDevelopers/piston#973]
It'd be nice to have a crate for translating `Touch` events into `Gesture` events (i.e. pinching, multi-finger swiping, etc). Gestures are often nice for zooming / navigating GUI's etc.

We might need to add a `Touch` event first though - i'm not sure if we have one yet or not? If not, there's a nice example of `Touch` events in glutin (see [here](https://github.com/tomaka/glutin/blob/master/src/events.rs#L79)).

**Comment by bvssvni** [comment]
I opened https://github.com/PistonDevelopers/piston/issues/974.

Suggestion for name: `piston-gesture`?

Could be part of this repo and reexported under the `piston` crate.

**Comment by bvssvni** [comment]
The SDL2 window backend now supports touch gestures, so it is now possible to start working on a gesture library.
