### ISSUE TITLE
Is there any methods for drawing on intermediate buffers?

### ISSUE THREAD

**Issue by xilec** [PistonDevelopers/piston#977]
Is there any API in Piston for drawing lines, simple figures and text on intermediate buffers? 
I suppose it sould be solution for issues like that Vinatorul/minesweeper-rs#22

**Comment by 46bit** [comment]
As far as I can tell there still isn't a way to do this. I'm surprised as it makes `piston` unsuitable for non-trivial dynamic graphics. 🙁

**Comment by bvssvni** [comment]
There's https://crates.io/crates/graphics_buffer

**Comment by 46bit** [comment]
@bvssvni Awesome, thank you!

**Comment by 46bit** [comment]
Drawing to that buffer is quite slow but does work for this use-case.

**Comment by bvssvni** [comment]
I also believe there is a way to read the framebuffer through OpenGL, but I haven't tried it. The framebuffer is a GL object similar to a texture.

**Comment by bvssvni** [comment]
Closing.
