### ISSUE TITLE
adding cargo tests for window and event_loop

### ISSUE THREAD

**Issue by DanTheColoradan** [PistonDevelopers/piston#981]
Hey all. What's the plan for testing? Would you accept pull requests with tests?

New to Rust, but have had a little bit of practice it. Decent with C++/CMake and perl. Passing knowledge of other languages.

Thanks! Daniel

**Comment by DanTheColoradan** [comment]
Or perhaps I could write examples into the rust code? (https://doc.rust-lang.org/book/testing.html#documentation-tests) Looking for some long hanging fruit :)

**Comment by xaviershay** [comment]
If there is some test coverage missing I'd personally love to see that added.

Pretty sure doing a pass through documentation/examples to make sure they're working+useful would be handy. (I just found a mistake in the README recently)

**Comment by xaviershay** [comment]
I'd personally love to see an example of how to play a wav file. I don't think piston has an abstraction for this, but SDL2 (a piston backend) supports it. The rust-sdl2 examples don't have an example of this, though code suggests it is possible.

I am going to have to figure this out myself at some point anyways - but seems like a generally desirable thing for games to be able to do. :)

**Comment by DanTheColoradan** [comment]
Tests (running `cargo test`):
    piston -> 0
    piston/src/ -> 0
    piston/src/window -> 0
    piston/src/event_loop -> 0
    piston/src/input -> 24

I believe that means I can start adding tests for window and event_loop. If not, someone let me know so I don't duplicate effort :smiley:

**Comment by DanTheColoradan** [comment]
And I think I'll do tests first unless they turn out to be too much above my head. I'll open another issue for examples once the tests are done.

And by examples, I mean examples that are right there in the code like they have for the rust-lang documentation.

**Comment by xaviershay** [comment]
sounds good, looking forward to seeing what you come up with!

**Comment by DanTheColoradan** [comment]
Thanks @xaviershay. I have just the start of unit tests for the window src. I submitted a pull request so we can keep track of it. Feedback is appreciated if you have any.
