### ISSUE TITLE
Run Piston on Redox OS

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#983]
See https://www.reddit.com/r/rust/comments/3mw67c/i_am_jackpot51_the_writer_of_redox_a_rust/

Anyone up for the challenge?

**Comment by Ticki** [comment]
This is a quite big task. But would definitely be cool! Note that Redox plans to be Linux compatible so this should be possible.

**Comment by bvssvni** [comment]
It might be easier by writing a custom graphics backend for it.

**Comment by Ticki** [comment]
We're at it.

**Comment by felipetavares** [comment]
How is this going?

**Comment by ticki** [comment]
We have Orbital, acting as a low-level graphics controller, then there is OrbTK, a high level tool-kit, and lastly there are the software renderes, Pixelcannon and Tetrahedrane.

**Comment by Thetoxicarcade** [comment]
hmmm.... @ticki what's your status on this?

**Comment by bvssvni** [comment]
Closing as outdated.
