### ISSUE TITLE
Dual license new projects under Apache 2/MIT

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/piston#991]
There is a concern of the right to use patents that an open source project uses. Normally, when you publish an open source project before patenting it renders the patent invalid. However, some countries are changing their patent system to new practices which has consequences for software. This leads to more worries about long term dependence on a library.

I think we should dual license projects under Apache 2/MIT for new projects in order to get around potential patent issues, unless they are ported from other projects with different licenses.

**Comment by bvssvni** [comment]
OK, nobody against this? Then we'll try to use dual license Apache 2/MIT in new projects. I wrote a page on the wiki https://github.com/PistonDevelopers/piston/wiki/Licenses-&-patents.

**Comment by Phrohdoh** [comment]
:+1: for anything and everything MIT.
