### ISSUE TITLE
Distribution HOWTO

### ISSUE THREAD

**Issue by timClicks** [PistonDevelopers/piston#996]
It's really great to see Piston grow. There will be many more successes, but here is one small one - it is the first time that I've ever been able to get working on any platform. It has broken through endless frustration with PyGame, pyglet, Nim's SDL layer and other "entry-level" tools.

Now that I have built a few toy projects, I've begun to wonder - is there a set of recommended instructions for distributing projects to end users? `cargo build --release` is great, but how do I cross-compile, bundle everything into `.msi`/`.app`/`.deb`/`.rpm`/...?

**Comment by xaviershay** [comment]
I don't know but am also interested in the answer. Also whether anyone has any success publishing to steam or app store?

**Comment by bvssvni** [comment]
I am also interested in this! There was a post somewhere a while back about cross compiling, but I can not find it.

**Comment by ryo33** [comment]
I started to develop a game with Piston and I may publish to steam.
It 
So I am also interested in this.

**Comment by bvssvni** [comment]
Maybe we could open up an issue for publishing to each platform? Could use the label "Information" on the issue so people can find it. Later, when we have a collection of such issues we could make a tutorial.

**Comment by bvssvni** [comment]
Closing as outdated. Feel free to open up a new issue.
